### ISSUE TITLE
IO to /dev/fd/* files or fifos

### ISSUE THREAD

**Issue by bakul** [kevinlawler/kona#110]
Try "/dev/stdout" 0:"hello world" or x:0:"/dev/fd/0". Try the same thing with a fifo device. mmap() should be used with normal files only. Others should be read or written as appropriate.

**Comment by tavmem** [comment]
As I understand it:
1) fifos are synonomous with "named pipes".  The fifo part of this issue would apply to BOTH the Linux/Unix/Cygwin builds and to the Windows (mingw-w64) builds.
2) On the other hand, the /dev/fd/* file part of this issue would apply ONLY to the Linux/Unix/Cygwin builds.  It would NOT apply to the Windows (mingw-w64) builds.

**Comment by tavmem** [comment]
On 32-bit Gentoo
$ ls/dev/fd
0  1  2  255

On 64-bit Cygwin
$ ls /dev/fd
0  1  2  31

On 64-bit FreeBSD
$ ls /dev/fd
0  1  2  3  4  5

As /dev/fd/0 is STDIN, it seems that Kona should treat it as ReadOnly
As /dev/fd/1 is STDOUT, and /dev/fd/2 is STDERR, Kona should treat them as WriteOnly.

I have no idea what 255, 31, 3, 4 and 5 represent, 
or how Kona should treat them (ReadOnly, WriteOnly, ReadWrite).
Do we need to support these in Kona?

**Comment by tavmem** [comment]
Oh, I guess that we need to support this on OSX also
On OSX
ls /dev/fd
0  1  2  3  4  5

**Comment by tavmem** [comment]
It is actually a bit more complex (and stanger)

On 32-bit Gentoo
~ $ ls /dev/fd
0 1 2 3
~  $ cd /dev/fd
/dev/fd $ ls
0 1 2 255

On 64-bit Cygwin
~ $ ls /dev/fd
0 1 2 3
~ $ cd /dev/fd
/dev/fd $ ls
0 1 2 31

On 64-bit FreeBSD and OSX
~ $ ls /dev/fd
0 1 2 3 4
~ $ cd /dev/fd
/dev/fd $ ls
0 1 2 3 4 5

**Comment by tavmem** [comment]
Now works for "/dev/stdout" 0:"hello world" and x:0:"/dev/fd/0".
Note that for x:0:"/dev/fd/0" Kona will continue to accept input into x until Cntl-d is sent.

It may be better to break on newline,
then this would also resolve issue #283

**Comment by tavmem** [comment]
Ok ... I'm ready to look at fifos.
A fifo implies IPC between 2 unrelated processes.  We already have working functionality for a Kona process  to act as a "server" for other (possibly multiple) Kona processes which would act as "clients".

In the fifo case, are the 2 processes both instances of Kona, or is one process some arbitrary other type?

**Comment by tavmem** [comment]
I guess, in the most general case, the other process can be non-Kona.

**Comment by tavmem** [comment]
So, for test purposes, I will use Kona on one terminal, and a shell process on the other terminal.

**Comment by tavmem** [comment]
More specifically (as a first test):
I create a fifo in terminal 1 using a shell process (mkfifo fifo1).
I start a Kona process in terminal 2.
I open fifo1 for reading in Kona (termainal 2).
I write to fifo1 from terminal 1:
- cat > fifo1
- aaaa

The objective is to get aaaa to show up in Kona.

**Comment by tavmem** [comment]
Clearly more complex than the /dev/fd/* case
Seems that I will need to call stat() on the file and then check whether it is a fifo (using S_IFIFO).
If it is a fifo, do not mmap().

**Comment by kevinlawler** [comment]
Mmap code is probably redundant if there is file descriptor code.

**Comment by tavmem** [comment]
Yes, I think that is the objective of this issue.  As Bakul wrote in the issue description:
> mmap() should be used with normal files only. Others should be read or written as appropriate.

If the file descriptor code shows that it is a normal file, use mmap(),
if it shows that it is a fifo, do not use mmap()

**Comment by kevinlawler** [comment]
Not doing it file-descriptor only was a mistake on my part. More versatile. Bakul ran a test that shows it's faster, too (with an appropriate buffer, on the tested systems), contrary to what I originally believed.

**Comment by tavmem** [comment]
I might be missing your point:
I thought we want to continue to use mmap() for normal files,
and mmap() simply does not work for fifos.
"Faster" does not enter into this issue, unless you are suggesting not to use mmap() on normal files.

**Comment by kevinlawler** [comment]
I'm saying `mmap` on normal files for `0:` was the wrong choice originally. Getting rid of it entirely would be inconvenient since the fixed-width field versions of `0:` depend on it.

**Comment by tavmem** [comment]
So to restate:
In Kona, `mmap` is used on normal files.
However, you surmise that in K, `mmap` is not used for normal files, and that by avoiding `mmap`, K gets faster results.  (A test by Bakul shows it's faster not to use `mmap`.)
However, getting rid of `mmap` in Kona would be inconvenient.

**Comment by tavmem** [comment]
Sounds like you have identified a new "optimization" issue for Kona.

**Comment by bakul** [comment]
On Sat, 25 Apr 2015 23:51:29 PDT Tom Szczesny <notifications@github.com> wrote:
> 
> So to restate:
> In Kona, `mmap` is used on normal files.
> However, you surmise that in K, `mmap` is not used for normal files, and that
>  by avoiding `mmap`, K gets faster results.  (A test by Bakul shows it's fast
> er not to use `mmap`.)
> However, getting rid of `mmap` in Kona would be inconvenient.

Sorry for tuning in late....

There are a number of tradeoffs but /now/ I think mmap can win
in many cases. First, I assume we want the entire file content
in memory so that common array operations can be done simply
-- you only worry about array limits, not buffer limits.

If you are reading in a very large file, mmap helps in two
ways:
1. You don't need to allocate a huge buffer upfront. This may
   not even always be possible on a heavily used machine and
   may force a bunch of swapping and swapping is death for
   performance. This is a waste if the data is only touched
   once -- why hang on to multi GB buffer during the entire
   operation?
2. System IO can overlap while the user process does array
   ops. In the read-in-the-whole-file case you have to wait
   until the whole file is read in.

Also recall that in 32bit address space machines often you
could not fit in a large vector in memory completely but this
is not a common problem in 64 bit address space machines --
not many people can afford to *have* petabytes of data, let
alone operate on them!

So I would leave in the mmap code!

You still need to deal with interactive IO (FIFOs, sockets,
terminals) but mainly for commands and displaying results
and that you operate on expression at a time.

For reading / writing data it makes sense to wait until the
entire operation can be completed. In my own C library I have
a function called file2string that can be used like so:

	size_t size
	char* contents = file2string(filename, &size)

It would do the right thing for a file, fifo or char device
and on return you have the contents of the whole file in a
single buffer.

**Comment by bakul** [comment]
To clarify the original issue, 

    f 0:x
    0:f

should do the right thing not just when f is a file but also when it is a device or a fifo. Whether it is /dev/fd/N or /dev/stdin or a named fifo, doesn't matter. Kona should use read()/write() syscalls instead of mmap(). Among other things this will allow you to create kona scripts that can be used in a unix shell pipeline.

**Comment by tavmem** [comment]
> Kona should use read()/write() syscalls instead of mmap().

Use read()/write() syscalls for a device or a fifo,
and use mmap() for a regular file?

Your prior comment suggested keeping mmap() for regular files.

**Comment by bakul** [comment]
On Sun, 26 Apr 2015 00:46:55 PDT Tom Szczesny <notifications@github.com> wrote:
> 
> > Kona should use read()/write() syscalls instead of mmap().
> 
> Use read()/write() syscalls for a device or a fifo,
> and use mmap() for a regular file?
> 
> Your prior comment suggested keeping mmap() for regular files.

Right.

**Comment by tavmem** [comment]
Terminal 1:
```
cd kona
mkfifo fifo
cat > fifo
```
Terminal 2:
```
cd kona
rlwrap ./k
x: 0: "fifo"
```
Terminal 1:
```
aaaaa

bbb
c
ddddddd
CNTL-d
```
Terminal 2
```
("aaaaa"
 ""
 "bbb"
 "c"
 "ddddddd")
```

**Comment by tavmem** [comment]
Does Kona need functionality to write to a fifo?

**Comment by tavmem** [comment]
Terminal 1
```
~/kona $ mkfifo fifo
~/kona $ rlwrap ./k
K Console - Enter \ for help

  "fifo" 0: "message\n"
  "fifo" 0: ("msg01\n";"\n";"m02\n";"message03\n")
```
Terminal 2
```
~/kona $ cat fifo
message
~/kona $ cat fifo
msg01

m02
message03
tom@xps ~/kona $ 
```

**Comment by 0branch** [comment]
Regression due to ff952fd:

	  `0:"hey\n"
	file error
	`0:"hey\n"
	 ^
	>

Is this intentional?

**Comment by tavmem** [comment]
Not intentional.
There was no test in the regression test suite to catch this.
Thanks!
