### ISSUE TITLE
script load error reporting

### ISSUE THREAD

**Issue by kevinlawler** [kevinlawler/kona#117]
Reported:

"When a file with an unmatched error is being read the interpreter silently stops executing the file at the line containing the unmatched string. For example, in the following file the definition of c is not loaded and no error is displayed:"

    \l script

    /script.k contents

    a: {x+y}
    b: {(x;y)
    c: {y+x}

Script loader should report error.

Can \s step be updated in a similar way?

**Comment by tavmem** [comment]
Fix for #363 re-opens this issue.
