### ISSUE TITLE
http GET request

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#210]
(FROM anon in Kona Developers):
(\`"www.google.com";\`http) 4: "GET /"
or 
(\`"http://ichart.yahoo.com";`http) 4: "GET /table.csv?s=GOOG"
should work with K3, no?
I'm getting a type error.

(FROM Kevin):
I don't remember this from any version of K I used. ​The syntax seems pretty odd to me, too: "`http" does not specify a port, and then the http plaintext is dictated instead of somehow handled. It also looks like it does socket-oblivious communication, which has its pros and cons however you implement it. As far as I know socket-oblivious communication has not been an allowance in K.

Implementing a synchronous and asynchronous socket-aware plaintext sends, to correspond with the K-IPC sends 3: and 4:, would be an easy and nice addition to Kona. You would get telnet and other plaintext socket services out of this too, not just HTTP. The K syntax would take some thinking. The C syntax would be hard to mess up. If anyone wants to add this they're welcome to try.The K syntax should be submitted to the list for review first.

See also: https://github.com/kevinlawler/kona/issues/79

(FROM Kevin):
Worth noting: 
a:`4:"curl -L google.com" 
  1#a

(FROM Bakul):
Try
	a:(\`"ichart.yahoo.com";`http) 4: "GET /table.csv?s=GOOG"
in K 3.2

(FROM Kevin):
I looked into this. Apparently it does respect ports, doesn't require 
socket/handle management, and doesn't handle HTTP redirects/etc. The 
token "`http" is a misleading choice. Ignoring the absence of handle 
management, it works a lot like the socket extensions described 
earlier the thread. This was a convenience method added via operator 
overloading. 

I think the idea of adding socketless sends via overloading is 
interesting. You could do 

(\`"localhost:1234";`ipc) 4: "a:1" 

for a socketless IPC send. 

Then perhaps you could do 

(h;\`http) 4: "GET /" 

for a stateful send, where h is an integer atom representing an "http" 
handle. Possibly you could open this handle using 

3: (\`"hostname";80;`http) 

Without looking I can't tell whether you can use the same handles for 
either IPC or HTTP. There is an IPC handshake so I think not. 

The token \`text or similar is perhaps a better choice than `http. 

I think HTTP redirects and the like should not be added. At that point 
you are reimplementing cURL.

**Comment by tavmem** [comment]
Kevin wrote:
> It also looks like it does socket-oblivious communication,

It might be that a socket is created with the associated IP address and a port== 80.

**Comment by tavmem** [comment]
Given what appears to be a "socket-oblivious" command that works:
~ $ curl -L google.com
these are my questions:

1) The DNS server apparently returns the IP address to my computer, and **cURL** (on my computer) then sends the request message to the IP address.  Is there way to get **cURL** to display the IP address that it uses?

2) Does the DNS server also return the port that should be used with the target IP address to **cURL**, or does **cURL** assume that it should use port 80?

3) Is there a way to get **cURL** to display the port that it uses to send the request message?

**Comment by tavmem** [comment]
It appears that DNS does not store port numbers.  So, it seems that **cURL** assumes port 80.

**Comment by tavmem** [comment]
Found it.
It's the verbose option:
```
~ $ curl -v http://www.google.com
* About to connect() to www.google.com port 80 (#0)
*   Trying 173.194.43.80...
* Adding handle: conn: 0x9998f60
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x9998f60) send_pipe: 1, recv_pipe: 0
* Connected to www.google.com (173.194.43.80) port 80 (#0)
```

**Comment by bakul** [comment]
Each "service" has a default port. For http it is port 80, ftp
is port 21 and so on. On unix machines /etc/services usually
lists this mapping and getservbyname() can be used to map a
symbolic name to its port number. I think k3 uses this so for
instance you can use ("wwww.google.com";`http) for getting a
comm handle. You can use a port number instead of a symbol.
But the service you are talking to may not use the default in
which case you must use a numeric port it wants. kref may
document some of this.

**Comment by tavmem** [comment]
Thanks! 
So, my plan for implementing
(\`"www.google.com";\`http) 4: "GET /"
in Kona is:
1) use libcurl to get an IP address from DNS (e.g., 173.194.43.80)
2) use port 80 for \`http
3) establish a communication handle, e.g., 3:(`"173.194.43.80";80)
4) send the request, e.g.,  h 4:"GET /"
5) return the result

**Comment by bakul** [comment]
On Fri, 08 May 2015 08:36:43 PDT Tom Szczesny <notifications@github.com> wrote:
> So, my plan for implementing
> (\`"www.google.com";\`http) 4: "GET /"
> in Kona is:
> 1) use libcurl to get an IP address from DNS (e.g., 173.194.43.80)

use gethostbyname(), instead of adding a dependency on libcurl.

> 2) use port 80 for \`http

if the port is a symbol `foo, use the port num from the result
of getservbyname("foo", "tcp").

you may want to put absolutely minimum os/machine dependent
code in a separate file for each combination and compile, link
it just on that target.

> 3) establish a communication handle, e.g., 3:(`"173.194.43.80";80)
> 4) send the request, e.g.,  h 4:"GET /"

you can directly use (host;port) instead of a handle. see
chapter 11 of kref. note that for http you may have to add
some headers as well as append \r\n\r\n at the end. i think
host: header may be required.

> 5) return the result

**Comment by tavmem** [comment]
Thanks!

**Comment by tavmem** [comment]
A note from Linux man-pages at http://man7.org/linux/man-pages/man3/gethostbyname.3.html

> The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() functions are obsolete.  Applications should use getaddrinfo(3), getnameinfo(3), and gai_strerror(3) instead.

**Comment by tavmem** [comment]
Some documentation to use for testing on different platforms (like Windows):

You can get a current IP address and port using the verbose option of cURL, e.g.,
curl -v http://www.google.com
might give you 173.194.43.81 and port 80

You can then test the 4 different command formats in a Kona process:
```
(`"www.google.com";`http) 4: "GET /"

(`"www.google.com";80) 4: "GET /"

(`"173.194.43.81";`http) 4: "GET /"

(`"173.194.43.81";80) 4: "GET /"
```
