### ISSUE TITLE
Moving Average

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#211]
(FROM Joe B. in Kona-Users):
Curious if there is any special code in Kona for moving averages. Searching all the documents I can find - i don't see anything on how to create a moving average in Kona not even on RossettaCode. I think J has some special code for moving averages and surprised to not find this for K/Kona. What am I missing?

(FROM Kevin):
Here's one: 
http://kx.com/a/kdb/examples/stock.t 

A few others that can be translated: 
https://www.google.com/search?q=kdb+moving+average 

It would be nice if to add simple moving averages / exponentially 
weighted/decaying moving averages here: 
https://github.com/kevinlawler/kona/wiki/Idioms 

And here: 
http://rosettacode.org/wiki/Averages/Simple_moving_average 

Good expository material on EDMA: 
https://github.com/StefanKarpinski/edma

(FROM Markus Sieber):
in kdb+ they implemented   x y\y. this can be used for having a fast exponential moving average function:
ema:{first[y](1-x)\x_y} 
actually  x y\z is an optimized  {z+y_x}[x;y;z]
i think this would also make sense for kona

**Comment by Eratosthenes** [comment]
I've added a simple function for calculating moving averages to Rosetta code. 

avg:{(+/x)%#x}
sma:{avg'x@(,\!y),(1+!y)+\:!y}

It doesn't calculate the trace of the input, so it uses O(n*p) memory rather than O(n^2) memory. 

However, this function is not "stateful", so while it will efficiently calculate SMA's for large arrays, it does not meet the requirements of the problem statement on Rosetta Code.

**Comment by Eratosthenes** [comment]
Okay, here is a stateful moving average in K:

```
  mavg:{a:x@&~_n~'x;avg a}
  sma:{n::x#_n; {n::1_ n,x; mavg n}}

  sma[5]' 1 2 3 4 5 5 4 3 2 1
1 1.5 2 2.5 3 3.8 4.2 4.2 3.8 3
```

**Comment by 0ihsan** [comment]
accumulative approach for relative/exponential moving average:
```
  length:3
  values:(1.0 2 3 4 5 6 7 8 9 10)
  ema:{{[a;e;x](a*x)+e*(1-a)}[2%x+1.0]}
  rma:{{[a;e;x](a*x)+e*(1-a)}[1.0%x]}

  ema[length]\values
1 1.5 2.25 3.125 4.0625 5.03125 6.015625 7.007812 8.003906 9.001953

  rma[length]\values
1 1.333333 1.888889 2.592593 3.395062 4.263374 5.175583 6.117055 7.078037 8.052025
```

see: https://www.tradingview.com/support/solutions/43000592270-exponential-moving-average/
