### ISSUE TITLE
Accessing enclosing function arguments from subfunctions.

### ISSUE THREAD

**Issue by paul7** [kevinlawler/kona#220]
There seems to be a somewhat minor problem: subfunction can correctly access enclosing function's local vars, but not its arguments unless they are explicitly named. E.g.:

  {{[a]a+x}}[1][2]

type error
  {t:x;{[a]a+t}}[1][2]

3
  {[x]{[a]a+x}}[1][2]

3

K2.8 evaluates these three expressions to 3, K4 doesn't know about subfunctions.

**Comment by tavmem** [comment]
See comments in issue #427

**Comment by tavmem** [comment]
Interesting results during this partially implemented state:
In Kona
```
  {{[a]a,x}}[1][2]
nyi error
>  \
  
  x:`p
  {{[a]a,x}}[1][2]
2 1                          / this is actually the correct result.
```

**Comment by tavmem** [comment]
Similarly, in a fresh session of Kona
```
  {{[a]a,x,y}}[1][2]3
nyi error
>  \
  x:`p
  y:`q
  {{[a]a,x,y}}[1][2]3
3 1 2                       / also, the correct result
```
