### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [kevinlawler/kona#270]
Would you like to add more error handling for return values from functions like the following?
- [munmap](http://pubs.opengroup.org/onlinepubs/9699919799/functions/munmap.html "Unmap pages of memory") ⇒ [_0d_write](https://github.com/kevinlawler/kona/blob/be4f0b6de3dc2352badda7311cdbac5198d87015/src/0.c#L113)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action") ⇒ [attend](https://github.com/kevinlawler/kona/blob/f4c21ea91d6330e743196056f224a34bbf20d898/src/kc.c#L175)

**Comment by elfring** [comment]
Are calls for functions like ["fopen" and "fclose"](https://github.com/kevinlawler/kona/blob/4e3d3b0f953103b4dca4d26c8b02af73ca0f7174/src/c.c#L56 "Checking file access calls?") further update candidates?

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Do you care for [failed malloc() calls](https://github.com/kevinlawler/kona/blob/a8fbaea4cf488d805b358a773d57c017fc1d3367/src/kc.c#L144 "Check recur().")?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by tavmem** [comment]
Yes, the information sources are useful.  Thanks!

**Comment by kirbyfan64** [comment]
I would personally just write an `alloc` function like so (in the K style ;):

```c
void* alloc(size_t sz) {
    void* r=malloc(sz);if(!r){fputs("out of memory\n",stderr);exit(1);}
    return r;
}
```

That way you can just do:

```
find ! -name file_containing_alloc_definition.c -exec sed -i {} 's/malloc/alloc/g' \;
```

**Comment by tavmem** [comment]
Sounds like a good idea.  Thanks!!

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Does "the K style" provide any [help for cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern "Description for cross-cutting concerns") in affected source files?

**Comment by kirbyfan64** [comment]
I'm pretty sure most static analysis tools would probably crash if they tried to work through this source code. They weren't really designed for this coding style.

**Comment by elfring** [comment]
Did you try any of such analysis tools out to see how much they could help to improve source code for this software here?

How do you think about to delegate any source code transformations to a tool like "AspectC++" or "Coccinelle"?

**Comment by tavmem** [comment]
The current priority is to close as many of the "optimization" and "enhancement" open issues as possible.  There are currently:
- 5 open optimization issues
- 12 open enhancement issues

Might get back to tools like "AspectC++" or "Coccinelle" at some later date.

**Comment by elfring** [comment]
How do you think about to let such tools perform specific software maintenance task for you (instead of fiddling with manual coding)?
Are there chances to benefit from automatic source code transformations to any degree?

**Comment by tavmem** [comment]
I am sure that all of these tools are worth evaluating.
They are simply not a priority at this time.  There are much more important issues.  For example,

@bakul recently wrote:
> there are still incompatibilities with k3. Steven Apter's site, nsl.com, has a number of examples that don't run in kona,

Identifying and addressing Kona/k3 incompatibilities are not easily done by automatic source code transformations.

**Comment by elfring** [comment]
Would you like to reopen this issue until the remaining implementation details will be fixed also in the affected C source files?

**Comment by tavmem** [comment]
Right now, it seems that we have handled all the outstanding cases.
We can always re-open this issue later, and re-check for error handling problems.

**Comment by elfring** [comment]
Would you like to care for [failed close() calls](https://github.com/kevinlawler/kona/blob/f939b96e11ab712b23acfb8451bd8d1fc594f95f/src/kapi.c#L40 "Check scd().")?

**Comment by tavmem** [comment]
Check error code on close()
b1ed4b9ee34a83c79901225b2172b90fface3356

**Comment by elfring** [comment]
Thanks for your source code improvements.
