### ISSUE TITLE
SIGBUS or wsfull error

### ISSUE THREAD

**Issue by bakul** [kevinlawler/kona#301]
y:256 _sv (8;8)#(1000?256);
      <y;

Tested on FreeBSD

**Comment by tavmem** [comment]
In both k3.2 and k2.8 a domain error occurs in the 1st statement:
```
   y:256 _sv (8;8)#(10?256);
domain error
y:256 _sv (8;8)#(10?256);
                   ^
> 
```

**Comment by tavmem** [comment]
In k3.2 and k2.8
```
  256 _sv 1
1
  256 _sv 1 1
257
  256 _sv 1 1 1
65793
  256 _sv 1 1 1 1                /reaches a max of 16843009
16843009
  256 _sv 1 1 1 1 1              /same as last result
16843009
```
In Kona
```
  256 _sv 1
1
  256 _sv 1 1
257
  256 _sv 1 1 1
65793
  256 _sv 1 1 1 1               /this is not a max
16843009
  256 _sv 1 1 1 1 1             /just keeps on going
4311810305
```

**Comment by tavmem** [comment]
But in this case k3.2 and k2.8 do not reach a max.
They continue up to (and beyond) overflow
```
  10 _sv 2#1
11
  10 _sv 10#1
1111111111
  10 _sv 11#1
-1773790777
  10 _sv 12#1
-558038585
```

**Comment by tavmem** [comment]
Actually, Kona does not overflow with 256 (and a vector of ones) either.
It reaches (and stops at) a higher max (64 bit)
```
  256 _sv 5#1
4311810305
  256 _sv 6#1
1103823438081
  256 _sv 7#1
282578800148737
  256 _sv 8#1
72340172838076673        /max
  256 _sv 9#1
72340172838076673
```

**Comment by tavmem** [comment]
However, you ultimately get overflow in Kona, k3.2 and k2.8
```
  (8;8)#(1000 _draw 256)                               /using Kona to generate vectors
(235 94 38 113 208 200 170 251
 216 147 99 64 1 90 76 69
 232 2 132 104 118 248 54 147
 66 225 245 97 48 155 120 62
 242 61 101 234 152 167 243 33
 109 163 28 56 211 216 62 94
 18 109 132 102 72 56 233 30
 39 110 156 171 125 182 77 129)
  
  256 _sv 235 94 38 113 208 200 170 251       /using Kona on the 1st generated vector
-1486708556709713157

    256 _sv 235 94 38 113 208 200 170 251     /using k2.8 on the 1st generated vector
-792155397
```

**Comment by tavmem** [comment]
So, the problem appears to be in "grade_updown" in Kona in file (vg.c), when using a vector of very large positive and negative integers.

**Comment by bakul** [comment]
In kona ints are 64bit long. _sv works fine though I haven't
tested boundary conditions. You can even display the array of
values. It is just the grade up that crashes and the crash
seems to be data dependent. From the error msg I suspect some
allocation is messed up.

**Comment by bakul** [comment]
On Tue, 17 Feb 2015 06:36:26 PST Tom Szczesny <notifications@github.com> wrote:
> 
> In both k3.2 and k2.8 a domain error occurs in the 1st statement:
> ```
>    y:256 _sv (8;8)#(10?256);
> domain error
> y:256 _sv (8;8)#(10?256);
>                    ^

It's _draw in k3.

**Comment by kevinlawler** [comment]
My guess is the check for distribution grade causes an overflow when you attempt to take the difference of a very large positive number and a very small negative number. There are two ways to solve that: cast the variables in question to `__int128` and take the difference there (preferred), or check that the difference is non-negative for big differences.

**Comment by tavmem** [comment]
Thanks!
__int128 is not supported on all target platforms ... so we need both.

**Comment by bakul** [comment]
On Tue, 17 Feb 2015 09:02:28 PST Kevin Lawler <notifications@github.com> wrote:
> 
> My guess is the check for distribution grade causes an overflow when you
> attempt to take the difference of a very large positive number and a very
> small negative number. There are two ways to solve that: cast the variables
> in question to `__int128` and take the difference there (preferred), or check
> that the difference is non-negative for big differences.

Why are you taking the difference? a <relational-op> b
shouldn't require double width operation.
