### ISSUE TITLE
Parsing inconsistency

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#305]
```
  f:{x _ss y}
{x _ss y}

  s:{x _ss y}
reserved error
>  \

  ss:{x _ss y}
parse error
>  \

  f:{x _ss y}
{x _ss y}
```

**Comment by buffis** [comment]
I guess you realized this already, but it's due to the varname being presence in the sequence of the function name. Strange.

>  s:{x _in y}
>  i:{x _in y}
reserved error
>  in:{x _in y}
parse error

**Comment by tavmem** [comment]
Yeah, thanks.  I mentioned this in a comment in issue #302:
>
Note that when Kona repeats back the function definition, it has placed an additional underbar in the reserved word "if". This is due to a faulty resolution to issue #288 (Named Recursion). The "f" in "if" is being mistaken for the name of the function.
>
Most likely, this is also causing the problem described in issue #305.
