### ISSUE TITLE
"error: thread-local storage not supported for this target"  on attempted build

### ISSUE THREAD

**Issue by RogueAnt** [kevinlawler/kona#308]
Output on attempted build is:  (32-bit MacBook (Intel core duo), under OSX Snow Leopard)

~/kona $ make
cc -g -O3  -fast   -c -o src/0.o src/0.c
In file included from src/0.c:19:
src/k.h:7: error: thread-local storage not supported for this target
make: *** [src/0.o] Error 1
~/kona $ 

I tried changing -lpthread to -pthread in the makefile but still get this message.

the gcc version is :

~/kona $ gcc -v
Using built-in specs.
Target: i686-apple-darwin10
Configured with: /var/tmp/gcc/gcc-5666.3~6/src/configure --disable-checking --enable-werror --prefix=/usr --mandir=/usr/share/man --enable-languages=c,objc,c++,obj-c++ --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin10 --with-gxx-include-dir=/usr/include/c++/4.2.1 --host=i686-apple-darwin10 --target=i686-apple-darwin10
Thread model: posix
gcc version 4.2.1 (Apple Inc. build 5666) (dot 3)

**Comment by tavmem** [comment]
One of my machines is a MAC with OS X, Version 10.

There are 2 C-compilers on my MAC.
The command **gcc --version** yields
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1

However, the command **cc --version** will describe the default C-compiler, and yields
Apple clang version 4.1
Thread model: posix

The Makefile is using **CC** which invokes the default C-compiler
On my MAC that would be **clang** not **gcc**

The Makefile only specifies that **CC=gcc** for the Win-64 and Win-32 builds.
The Makefile will use the default compiler on a MAC (whatever that is).
(Also note that changing -lpthread to -pthread will only affect the Win-64 and Win-32 builds.)

What is the default C-compiler on your MacBook?

**Comment by tavmem** [comment]
It would be good to know which C-compiler is being used when this error occurs.
Please execute the command
cc -v
on your 32-bit MacBook and let me know what you get.

**Comment by kirbyfan64** [comment]
Maybe [this](http://www.drdobbs.com/architecture-and-design/implementing-thread-local-storage-on-os/228701185) would be of use?

**Comment by tavmem** [comment]
Thanks!
The article states that this problem occurs on OS X when using gcc.

Since I have had no problems when using **clang** on OS X, I am going to assume that RogueAnt's default  C-compilier on the 32-bit MacBook is gcc.

There appear to be (at least) 2 solutions:
1) Implement TLS on OS X for gcc as described in the article (which apparently would be 10 times slower than simple access to a shared global).
2) modify the code to use simple shared globals when using gcc with OS X.

**Comment by tavmem** [comment]
On the other hand Clang is an open source product developed by Apple.
It is not unreasonable to assume that anyone with OS X can get access to Clang.
Probably best just to modify the Makefile to specify using Clang with OS X.

**Comment by kevinlawler** [comment]
Are we actually using multi-threading anywhere? If not, here is a possible solution: replace all designations of thread-local storage by different but similarly named macro which compiles to nothing. If it becomes necessary to enable thread-local storage than the macro can be defined correctly. Certain operations would speed up: in my experience thread-local storage, as implemented by the compilers, can be slow.

**Comment by tavmem** [comment]
The only place that I know of that actually uses multiple threads is in the Windows build.  One thread handles console input/output, the other thread handles sockets for client/server sessions.
Threads would need to be activated for Windows.

**Comment by kirbyfan64** [comment]
@tavmem Then why do it as @kevinlawler said and define the macro to the proper expansion on Windows only?

**Comment by kevinlawler** [comment]
@kirbyfan64 Chances are special casing it for Windows just restricts the problem to that platform, which doesn't solve the problem. If it compiles on Windows it might be OK.

**Comment by kirbyfan64** [comment]
@kevinlawler I though the only issue was on Macs running GCC...

**Comment by tavmem** [comment]
The problem does only occur on Macs running GCC.

Kevin's suggestion works in either of the 2 ways
1) redefine "__thread" to nothing only for OSX
2) redefine "__thread" to nothing for everything but WIN32.

Since we are only using threads in WIN32, the 2nd option is probably better,
however, I don't see a noticeable speedup on Linux after making the change.

**Comment by tavmem** [comment]
Just as an FYI:
Redefining "__thread" to nothing on Windows did cause the build to fail there.
