### ISSUE TITLE
Curried application

### ISSUE THREAD

**Issue by JohnEarnest** [kevinlawler/kona#309]
I was working on simplifying an implementation of a cross-product, and I was surprised at the results:

	  {{m:{*/x@'y}[x];m[y]-m[|y]}[(x;y)]'(1 2;2 0;0 1)}[2 3 4;5 6 7]
	-3 6 -3
	  {m:{*/x@'y}[(x;y)];{m[x]-m[|x]}'(1 2;2 0;0 1)}[2 3 4;5 6 7]
	(-1 1
	 2 -2
	 -1 1)

Simplifying, these fragments seem to illustrate the issue. I would expect both of these to produce the same result. The second looks correct, and the first looks like it isn't applying `m`?

	  {m:{x,'y}[(x;y)]; {m[x]}[-4]}[7;15]
	-4
	  {m:{x,'y}[(x;y)]; m[-4]}[7;15]
	(7 -4
	 15 -4)

If I'm missing something I'd appreciate an explanation.

**Comment by tavmem** [comment]
Looks like a bug.  k2.8 yields the following results:
```
  {m:{x,'y}[(x;y)]; {m[x]}[-4]}[7;15]
(7 -4
 15 -4)
   {m:{x,'y}[(x;y)]; m[-4]}[7;15]
(7 -4
 15 -4)
```

**Comment by JohnEarnest** [comment]
Simpler reproduction case:

	  {m:{x,y}[5]; {m[x]}[3]}[]
	3
	  {m:{x,y}[5]; m[3]}[]
	5 3

The problem does not occur at the global scope:

	  m:{x,y}[5]; {m[x]}[3]
	5 3

**Comment by tavmem** [comment]
Need a data structure that provides a more reliable mechanism for going back up the tree that defines grandparent, parent, child relationships of subfunctions.
The current fix that I have for this issue breaks four other regression tests:
```

Failed. These are not equal:
9 , {+/x,{x+y,{x-{x+{b:3; g:{b}; b:4; g[]}0}5}12}[1;2]}1
********************************
9
--------------------------------


Failed. These are not equal:
7 , {+/x,{x+y,{x-{x+{b:3; g:{b}; b:4; g[]}0}5}12}[1;2]; :7}1
********************************
7
--------------------------------


Failed. These are not equal:
8 , {({b:3;g:{b};b:4;g[]}0) + {b:5;g:{b};b:6;g[]}0}0
********************************
8
--------------------------------
10


Failed. These are not equal:
25 , {{+/x,{x+y,{x-{x+{b:3;g:{b};b:4;g[]}0}5}12}[1;2]}1 + {x+{b:3;g:{b};b:4;g[]}0}5 + {x-{x+{b:3;g:{b};b:4;g[]}0}5}12 + x}4
********************************
25
--------------------------------
```

**Comment by JohnEarnest** [comment]
I don't know how helpful this will be, but in my [K implementation](https://github.com/JohnEarnest/ok) I represent things as follows:

- All name-value bindings are stored in an [Environment](https://github.com/JohnEarnest/ok/blob/gh-pages/oK.js#L487)- basically just a dictionary which can be attached to a parent and for which lookups chain back through parents to the root. This is a normal implementation strategy for interpreters of functional languages.

- Every function invocation [attaches](https://github.com/JohnEarnest/ok/blob/gh-pages/oK.js#L549) a new Environment to a chain immediately before pairing up arguments and the names in the function's argument list.

- Nested functions need to be bound to their lexically enclosing environment. Thus, instead of using the _caller_'s environment as a parent to new Environments as described above, I use an enclosing environment tagged on the function object itself. At time of creation this environment is unbound. Whenever I [evaluate](https://github.com/JohnEarnest/ok/blob/gh-pages/oK.js#L601) a function literal which is not already bound to an environment (meaning I'm evaluating it in its definition site) I attach the current environment to that function.

I still have a lot of trouble grokking Kona's codebase, so I don't know how similar this is to the existing approach or how hard it would be to adapt.

**Comment by tavmem** [comment]
Thanks! 
I plan to try out a few different approaches.
