### ISSUE TITLE
{{x}[x;];y}[1;2]  produces segfault

### ISSUE THREAD

**Issue by buffis** [kevinlawler/kona#310]
{{x}[x;];y}[1;2] produces a segmentation fault

**Comment by tavmem** [comment]
This issue no longer crashes. Kona now yields
```
  {{x}[x;];y}[1;2]
valence error
>
```
However, k2.8 yields
```
  {{x}[x;];y}[1;2]
2
```
Looks like a bug.

**Comment by tavmem** [comment]
Simplification:
In k2.8
```
  {x}[1;]
{x}[1;]
```
Currently, In Kona
```
  {x}[1;]
valence error
>
```

**Comment by tavmem** [comment]
Although it is a valid form in k2.8, it's not clear how it would be used.
In k2.8 and in k3.2:
```
  f:{x}[1;]
  f 2
valence error
f 2
^

  f[1;2]
valence error
f[1;2]
^
```
But, of course, since it is a valid form
```
  f;2
2

  {{x}[1;];y}[1;2]
2
```
What is the point of having a "valid" form if it yields "valence error" whenever you use it?
Seems like a bug in k2.8 and k3.2.
Am I missing something?

**Comment by tavmem** [comment]
In k2.8 and k3.2
```
  +[1;]2
3
  *[1;]2
2
  -[1;]2
-1
  {x}[1;]2
valence error
{x}[1;]2
^
```

**Comment by tavmem** [comment]
k2.8 and k3.2 provide "run-time" error reporting on this.
Kona currently provides "parse-time" error reporting (which, is arguably better).

**Comment by buffis** [comment]
Just as a FYI since I reported this. I don't see any issues with the way Kona handles that when giving valence errors, since I don't really think the behavior is specified for this (as far as I can see).

I was mostly reporting the segfault (which was obviously a bug)

**Comment by tavmem** [comment]
I am closing this issue.
