### ISSUE TITLE
Segfault with golfed function

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#311]
http://codegolf.stackexchange.com/a/47782/21009

This works (as seen in the link):

```
f:{s:x;n:z;`0:(,s@!n),({s[(#s)+-2-x],({" "}'!n-2),s@n+x}'!y-2),,(|s@!-4+#s)@!n}
```

but this segfaults:

```
f:{s:x;n:z;`0:(,s@!n),({s[-2-x+#s],({" "}'!n-2),s@n+x}'!y-2),,(|s@!-4+#s)@!n}
```

Toying with this example will yield several other segfaults.

**Comment by JohnEarnest** [comment]
Took a little while to try to boil this down to a smaller reproduction case. It looks like this is enough to produce a crash:

	{{x[2]}[x],0}["AB"]

Stripping off that inner lambda will produce an index error, as expected:

	  {x[2],0}["AB"]
	index error

Something about nested lambdas is interfering with Kona's index checking.
