### ISSUE TITLE
64-bit Windows release wsfull

### ISSUE THREAD

**Issue by joebo** [kevinlawler/kona#317]
The 64-bit Windows release appears to be limited to 4GB of memory. If so, is this documented anywhere or is it possible to compile with more addressable memory?

On Windows:
>  \t 600000000#("aa";"bb")
2
wsfull error
600000000#("aa";"bb")
         ^

On Linux:
  \t 600000000#("aa";"bb")
12770

**Comment by tavmem** [comment]
Do both of your systems have the same amount of physical memory?

**Comment by joebo** [comment]
Yes. The Linux version was running in a virtualbox on the same machine
after I had the error.

It seems to give the wsfull at exactly 4gb

**Comment by tavmem** [comment]
It's not clear why that would happen.  There is no intentional limit built in (and hence, no documenation).
Will have to research this further.

PS: Thanks for reminding me to update the Windows version with fixes made since 2/23/15 on 8 issues: 302 revision, 305, 306, 309, 311, 313, 314 and 316.

**Comment by joebo** [comment]
Thank you, are you able to replicate it?

Also, many thanks for continuing to develop kona. I used it a little almost 2 years ago (https://github.com/kevinlawler/kona/issues/208) and since moved on to J, then recently came back to playing with the free kdb+ and kept bumping into the memory limit. That brought me back to kona and hoping I can work with large datasets on Windows

**Comment by tavmem** [comment]
My Windows system is 8.1 on a Dell Inspiron laptop with exactly 4.00 GB of memory.  So, I can't replicate the problem right now, but I can probably get a bigger system at some point.  It is an interesting "coincidence" that the limit you experince is exactly 4gb.

How big are you attempting to go?
I understand the limit in free kdb+, but is there also a limit when using J?
Why have you chosen "large dataets ***on Windows***"?

**Comment by joebo** [comment]
I haven't hit any limits with J. It has handled everything I have thrown at
it and has been a joy to learn. I have used it to work with files up to
9gb, 60 million+ rows.

Both J and R can deal with those sizes without too much difficulty. I have
an R process at 17gb of ram at the moment and will have J go up to 12gb at
times

I am using Windows as that's the standard environment where I work, but I
can boot up a virtualbox or run a vps if needed

**Comment by joebo** [comment]
Can you provide any additional build steps for win64? 

I downloaded the mingw-x86_x64 cygwin pacjage and wasn't sure if I should be building under the cygwin console or dos. I had some problems getting mingw configured under cygwin and have used it many times under dos with GnuWin32 make. I will try that tomorrow but wasn't sure about all the prerequisites

**Comment by tavmem** [comment]
I can get you some additional build steps later today (or maybe tomorrow).
As a start, I don't use Cygwin any more.  The first Windows executables were done with Cygwin, but then I needed to distribute the Cygwin API as well.
Currently, I am using MingGW-w64 and msys.  (I probably should switch to msys2.)
The build is done in an msys console.

**Comment by joebo** [comment]
I was able to build it and will post some steps to the wiki later.

It is failing in the mmap call. I will research further and will let you
know what I find. I needed to build it to get this far.

**Comment by joebo** [comment]
I was able to resolve the issue by compiling with -D_FILE_OFFSET_BITS=64

The root cause of the issue is in [mman.c](https://github.com/kevinlawler/kona/blob/master/src/win/mman.c#L80)

It will only set the dwMaxSizeHigh if the off_t size is different than DWORD

const DWORD dwMaxSizeHigh = (sizeof(off_t) <= sizeof(DWORD)) ?
                    (DWORD)0 : (DWORD)((maxSize >> 32) & 0xFFFFFFFFL);

Both are 4 bytes by default. off_t transparently becomes off64_t, which is 8 bytes, if _FILE_OFFSET_BITS=64 is set. This will cause it to set dwMaxSizeHigh appropriately

I will punt on whether the best solution is to update the Makefile for windows 64 or if it's to update mman.c to use a different approach. Since mman.c is copied from mman-win32, it might make more sense to just set the compiler flag.

http://stackoverflow.com/questions/3221113/off-t-without-d-file-offset-bits-64-on-a-file-2gb

**Comment by tavmem** [comment]
I'm curious as to which version of MinGW-w64 you ended up using.
The site http://mingw-w64.yaxm.org/doku.php/download
has 3 versions:
1) the Cygwin version
2) the Mingw-builds project
3) the Win-builds version

Just as an FYI, I am using the Mingw-builds project.
If you used one of the other versions, that is probably the reason that the Makefile would need to be changed.

**Comment by joebo** [comment]
I'm fairly sure I used http://sourceforge.net/projects/mingw-w64/, which is
the same as you. That would also explain why your released binary has the
same issue.
