### ISSUE TITLE
Issue with currying (f/[n;x])

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#325]
After being beaten at code golf (again), I noticed another K answer [here](http://codegolf.stackexchange.com/a/48796/21009) which was much shorter than mine. The answer was:

```
_mul[(3 5;1 3)]/[;1 0]
```

The person then wrote:

> This will not work in Kona, because for some reason `f/[n;x]` isn't implemented correctly. Only the `n f/x` syntax works, so the shortest fix is `{x _mul[(3 5;1 3)]/1 0}` at 23 char.

**Comment by tavmem** [comment]
In both k2.8 and k3.2
```
  _mul[(3 5;1 3)]/[;1 0]
{x _dot\:y}[3 5
 1 3)]/[;1 0]
```
That is the "correct" answer to a golf question?

**Comment by kirbyfan64** [comment]
@tavmem Well, you call it afterwards with the number you want:

```
_mul[(3 5;1 3)]/[;1 0] 5 / should output 1968 880
```

Otherwise, maybe the answer's wrong...

**Comment by tavmem** [comment]
Yes, I get
1968 880
in k2.8
Thanks, the answer looks correct.

**Comment by tavmem** [comment]
Simplification of the problem:
In k2.8
```
  (3 5;1 3)/[;1 0]
(3 5
 1 3)/[;1 0]
```
In Kona
```
  (3 5;1 3)/[;1 0]
(5 3
 3 1)
```

**Comment by tavmem** [comment]
Further simplification:
in k2.8
```
  3/[;1]
3/[;1]
```
in Kona
```
  3/[;1]
valence error
> 
```

**Comment by tavmem** [comment]
f/[n;x] does work in Kona (when used in a straightforward manner).
In both k2.8 and Kona
```
  5 _mul[(3 5;1 3)]/1 0
1968 880
```
and in both k2.8 and Kona
```
  _mul[(3 5;1 3)]/[5;1 0]
1968 880
```
As noted in the title of this issue, it is the currying of f/[n;x] that causes a problem in Kona.
```
  _mul[(3 5;1 3)]/[;1 0] 5
index error
```

**Comment by tavmem** [comment]
A simpler example of the same problem in Kona
```
  f:{x+1}
{x+1}
  3 f/1
4
  f/[3;1]
4
  f/[;1] 3
break error
x+1
 ^
>  
```
The curried form goes into an endless loop and needs to be broken with Ctl-c.

**Comment by tavmem** [comment]
Still simpler.
In Kona, you can generate a similar endless loop with
```
  f:{x+1}
{x+1}
  f/[;1]
break error
x+1
 ^
>
```

**Comment by tavmem** [comment]
Some notes on current status and what needs to be done:
This fails {x+1}/[;11] 2
because {x+1}/ has valence of 1.
This works {x+1}/[2;11]
only because of a hack to make it work like 2{x+1}/11
But the fact that this works 2{x+1}/11
seems to also be a hack, since {x+1}/ has valence of 1.

Seems that {x+1}/ should have a valence of 2
and we need to unwind the hacks that make {x+1}/[2;11] and 2{x+1}/11 currently work with valence of 1.

**Comment by tavmem** [comment]
Further complication from k2.8: 
If a function f has valence 1 then f/ has valence 2 and f/ iterates 
f:{x\*2}
f/[2;4] is 4\*2\*2 which is 16

If a function g has valence 2 then g/ also has valence 2 and g/ does not iterate
g:{x\*y}
g/[2;4] is 2\*4 with is 8

**Comment by tavmem** [comment]
Well, (obviously) that is why this feature is called "over monad".
