### ISSUE TITLE
test a merge of the Android-build process developed by kirbyfan64

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#327]
I cloned https://github.com:kirbyfan64/kona to a 32-bit Linux system and ran "make".
I got the following results:
```
arm-linux-androideabi-gcc -g -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -mtune=xscale -msoft-float -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3    -c -o src/0.o src/0.c
make: arm-linux-androideabi-gcc: Command not found
make: *** [src/0.o] Error 127
```

**Comment by kirbyfan64** [comment]
The error was a small typo in the makefile; try changing line 9 from `ifeq` to `ifneq`.

**Comment by tavmem** [comment]
Please make the change in your repository (so that we are ready for a merge when it works).
Then I will re-test in 32-bit Linux (Gentoo).

If that works, I will test in
- OSX
- Windows (32 and 64 bit)
- 64 bit FreeBSD
- 32 bit ARM (Debian)

When it works in all of the above (with any required changes) you will need to check that it still works in Android (as I don't have that environment yet).

**Comment by kirbyfan64** [comment]
@tavmem Fixed.

**Comment by tavmem** [comment]
All 6 systems look fine: the build works and the full test suite runs with no errors.
Please set up a pull-request.

**Comment by kirbyfan64** [comment]
@tavmem Unfortunately, somewhere along the way, I got it working in the Android AVD but broke it on my Nexus 5. :(

**Comment by kirbyfan64** [comment]
@tavmem Actually, it works; I was accidentally using the wrong version of the binary.
