### ISSUE TITLE
Error Trap

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#332]
This issue was also identified by theosjp in the Kona-Users forum:
in k2.8
```
  b:.[+;(1;"b");:]
  b[0]
1
  b[1]
"type"
```
Note that there is no error message on on the initial assignment to b
in Kona
```
  b:.[+;(1;"b");:]
type error
b:.[+;(1;"b");:]
    ^
>  \
  b[0]
0
  b[1]
1
```
You get an error message immediately (which is probably better than k2.8).
BUT ... the values of b[0] and b[1] seem wrong.

**Comment by bakul** [comment]
On Tue, 05 May 2015 08:58:47 PDT Tom Szczesny <notifications@github.com> wrote:
> 
> This issue was also identified by theosjp in the Kona-Users forum:
> in k2.8
> ```
>   b:.[+;(1;"b");:]
>   b[0]
> 1
>   b[1]
> "type"
> ```
> Note that there is no error message on on the initial assignment to b
> in Kona
> ```
>   b:.[+;(1;"b");:]
> type error
> b:.[+;(1;"b");:]
>     ^
> >  \
>   b[0]
> 0
>   b[1]
> 1
> ```
> You get an error message immediately (which is probably better than k2.8).

.[f;x;:] is for trapping an error.  An immediate error message
is not appropriate (this may happen in a server for example).
The result is (0; f . x) in case of success or (1; "text") in
case of an error.  See "error trap" in the reference.
