### ISSUE TITLE
Self-reference and IO Verbs

### ISSUE THREAD

**Issue by JohnEarnest** [kevinlawler/kona#335]
I noticed an odd behavior today:

      {`0:$x<0}5
    0
    
      `0:{$x<2}5
    0  
  
      `0:{$x<0}5
    type error
    `0:{$x<_f}5
          ^

For some reason, using the output verb `0:` to the left of a function seems to be causing the number `0` to be treated as a reference to the function.

Is Kona matching the pattern `x:{x}` in general and transforming it into `x:{_f}`?

**Comment by tavmem** [comment]
Yes, it is matching the pattern ...
but obviously, with some bugs.
