### ISSUE TITLE
.[ {. x}; "2+2"; : ] yields valence error

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#337]
This issue was identified by @teozabishi.
in Kona:
```
  .[ {.x}; "2+2"; : ]
(1
 "valence")
```
In k2.8, I get
```
  .[ {.x}; "2+2"; : ]
(0;)
```
However, theo reports that (when using k2.8) he gets
```
  .[ {.x}; "2+2"; : ]
0 4
```
which appears to be a correct result.
But when I use k2.8 I get
```
  ."2+2"
4
  {x}"2+2"
"2+2"
  {.x}"2+2"    // yields null
  .[ {.x}; "2+2"; : ]
(0;)
```
Not clear (yet) why theo is getting a different result than I am (with k2.8).
In either case, Kona appears to have a bug.
But, what is **the** correct result?

**Comment by teozabishi** [comment]
tom,

can you please try to add on your side - that might be what explains our
k2.8 testing diffs:

.[{.  x};"2+2";:]

Thanks,
Theo.

**Comment by tavmem** [comment]
Good catch!
The "space" makes all the difference:
```
  .[ {. x}; "2+2"; : ]
0 4
```
Thanks.

**Comment by tavmem** [comment]
Some corner cases that help clarify the problem (in Kona):
```
  .[ {x}; "2"; : ]
(0;"2")
  .[ {x}; "2+2"; : ]
(1
 "valence")
  
  .[ {x}; 1; : ]
0 1
  .[ {x}; 1 2; : ]
(1
 "valence")
```

**Comment by tavmem** [comment]
I have gone back to the commits of 12/31/2010 and the same problem exists.
This is not a regression bug.
It is a feature that has not been implemented.

**Comment by tavmem** [comment]
Trying all four "corner cases" in k2.8, I get the following results:
```
  .[ {x}; 1; : ]
0 1
  .[ {x}; 1 2; : ]
(1;"valence")

  .[ {x}; "2"; : ]
(0;"2")
  .[ {x}; "2+2"; : ]
(0;"2+2")
```
It is only in the last of the 4 cases in which there is a difference between Kona and k2.8.

**Comment by tavmem** [comment]
Now, a client process (in Linux) yields the following results:
```
  3: (`"127.0.0.1";8200)
3
  3 4: ".[{. x};\"2+`a\";:]"
(1
 "type")
  3 4: ".[{. x};\"2+2\";:]"
0 4
