### ISSUE TITLE
Regressions

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#338]
There are two regressions I have noticed:

- Reading from stdin via ``0:` `` gives a `file error`. It worked before...
- [b.k](https://github.com/kirbyfan64/b.k) no longer works. Formerly, this:
    
    ```
    echo abc | k myscript.k
    ```

    would set the `stdin` to `abc`. Now it tries to interpret the input as a K script.

**Comment by tavmem** [comment]
Fixed the read from stdin.

Can you please check to see whether b.k works properly?

**Comment by kirbyfan64** [comment]
Yup! Works now. Thanks!
