### ISSUE TITLE
Functions and Lexical Scope

### ISSUE THREAD

**Issue by JohnEarnest** [kevinlawler/kona#341]
Having more than one nested function seems to interfere with lexical bindings of variables in some cases:

      {[m] {}[]; {x;m}'1 2} 5
    (;)
      {[m]       {x;m}'1 2} 5
    5 5

It appears that when the function `{x;m}` is evaluated in the former case `m` gets a nil binding while in the latter case it inherits the binding from the surrounding function. I think the latter behavior is the most desirable, but any consistent behavior is acceptable.

The adverb in the above example appears to be necessary to observe this behavior:

      {[m] {}[]; {x;m}[1]} 5
    5
      {[m]       {x;m}[1]} 5
    5

**Comment by tavmem** [comment]
k2.8 supports the latter behavior:
```
  {[m] {}[]; {x;m}'1 2} 5
5 5
  {[m]       {x;m}'1 2} 5
5 5
```

**Comment by tavmem** [comment]
The adverb is not always necessary to produce problematic behavior.  In Kona:
```
  {[m]{}[];{x;m}[1]}5
5
  {[m]{}[];{x;m}1}5       //null
```
In k2.8
```
  {[m]{}[];{x;m}[1]}5
5
  {[m]{}[];{x;m}1}5
5
```
