### ISSUE TITLE
At Each Each

### ISSUE THREAD

**Issue by JohnEarnest** [kevinlawler/kona#342]
I discovered an inconsistency between Kona and K2.8 which may be a bug. Given a matrix `m`:

    m: (1 4 3 5 2
        3 2 5 2 3
        5 2 4 2 1)

K2.8 produces the result I would expect for the given expression:

      (m@')'(0 1 1;1 2 3)
    (1 2 2
     4 5 2)

(Given that the following works in both K2.8 and Kona:)

      m@'(1 2 3)
    4 5 2

Kona, however, seems to interpret this as a partial application of "amend" (I think):

      (m@')'(0 1 1;1 2 3)
    ((1 4 3 5 2
       3 2 5 2 3
       5 2 4 2 1)@'[0 1 1;;;];(1 4 3 5 2
       3 2 5 2 3
       5 2 4 2 1)@'[1 2 3;;;])

If this behavior is intentional I'd appreciate an explanation of what I'm doing wrong.
(This and my last two bug reports were the result of tinkering with a code golf problem. Adventures in exercising previously untouched edge-cases!)

**Comment by tavmem** [comment]
I doubt that it is intentional.
Most likely ... a bug.

**Comment by tavmem** [comment]
A manifestation of the problem in a simpler form:
In k2.8:
```
  m:3 3#"abcdefghi"
  m
("abc"
 "def"
 "ghi")

  m@'0 1 1
"aeh"
  
  f:m@'
  f
("abc"
 "def"
 "ghi")@'

  f 0 1 1
"aeh"
```
In Kona:
```
  m:3 3#"abcdefghi"
("abc"
 "def"
 "ghi")
  
  m@'0 1 1
"aeh"
  
  f:m@'
("abc"
  "def"
  "ghi")@'
  
  f 0 1 1
("abc"
  "def"
  "ghi")@'[0 1 1;;;]
```

**Comment by tavmem** [comment]
This was not a regression bug.
"At Each Each" was never implemented.
Changing this to a "feature".
