### ISSUE TITLE
Consistency on Read-from-stdin

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#350]
in both k2.8 and Kona-for-Windows:
```
  0:`
abc
"abc"
```
but, in Kona-for-Linux/Unix:
```
  0:`
abc
def
ghi
("abc"
 "def"
 "ghi")
```
Kona-for-Linux/Unix allows input of multiple lines of data until cntl-d (EOF) is found.
k2.8 and Kona-for-Windows accepts only 1 line of data.

Though the Kona-for-Linux/Unix approach is a valid implementation (and some might consider it a better approach) it is important for Kona to be consistent on all platforms and (at least for version 1 of Kona) it is probably best to have that consistency match k2.8.

**Comment by kirbyfan64** [comment]
Will there still be a way to read all input lines?

**Comment by tavmem** [comment]
If that is important, I can leave the current behavior for Kona-Linux/Unix and try to get Kona-Windows to accept multiple lines of input.
That would break compatibility with k2.8, but backwards compatibility is a lower priority than having Kona be consistent on all platforms.

**Comment by tavmem** [comment]
An associated current break between k2.8 and Kona-Linux/Unix:
When reading a single line of data in Kona-Linux/Unix (using cntl-d to stop) the result is:
```
  0:`
abc
,"abc"
```
which is a list composed of 1 element (which is a character array).
In k2.8
```
  0:`
abc
"abc"
```
the result is NOT a list, just a character array.
If we keep multiple-line-input in Kona, the single-line case could be demoted so the result is not a list.

**Comment by kirbyfan64** [comment]
*sigh* I've wanted to read just one line before, but I like having a multi-line input operation.

What does k2.8 return with no more input? The empty string?

**Comment by tavmem** [comment]
In k2.8, as soon as you hit Return, the interpreter takes off and processes the input.
If you just hit Return, k2.8 will yield the empty string.
Using the k2.8 strategy, if you wanted to collect multiple lines of input, you could set up a k-script to keep looking for input until it receives an empty striing.
This may be adequate.

**Comment by kirbyfan64** [comment]
What about pressing `Ctrl-D`, a.k.a. EOL?

**Comment by tavmem** [comment]
Not clear as to what context you are referring to.
Currently we have multiple inconsistencies:

If you are in k2.8, and only enter Ctrl-D, k2.8 yields null.
If you are in the process of entering  line "abc" Ctrl-D, the Ctrl-D is ignored.

If you are in Kona-Linux/Unix, and only enter Ctrl-D, you get the empty list.
If you are in the process of entering a line "abc" Ctrl-D, the Ctrl-D is ignored.
If you have entered one or more lines, entering Ctrl-D completes the input.

If you are in Kona-Windows, and only enter Ctrl-D, you get ,"\004" (End of Transmission).
If you are in the process of entering a line "abc" Ctrl-D, you get "abc\004".

**Comment by kirbyfan64** [comment]
> If you are in k2.8, and only enter Ctrl-D, k2.8 yields null.

This. So, basically, to read all of stdin in k2.8, it'd be something like:

    -1_{~6=4:*-1#x}{x,0:`}/("")

which would read the input until null is entered and then return everything but the trailing null. Long, but I guess it'll work...

**Comment by tavmem** [comment]
Yes, that would work in k2.8 if you wanted the result to be a single character array:
```
  -1_{~6=4:*-1#x}{x,0:`}/("")
abc
def
ghi
"abcdefghi"
```
If you wanted a list of individual line inputs, you would need a somewhat different k-command.

**Comment by kirbyfan64** [comment]
Ah, right:

    -1_{~6=4:*-1#x}{x,,0:`}/("")

Still feels long, though.

Also, while toying with things, I found another slight difference between Kona and k2. Try running the following program:

    `0:("abc";"def")

With k2, it prints an empty newline afterwards. With Kona, it doesn't print another newline and instead prints two spaces...?

I ran them like so (saved it to `y.k`):

    echo | k2 y
    echo | k y

Whether or not the empty newline is wanted, the two spaces are weird.

**Comment by tavmem** [comment]
Thanks for identifying the additional difference!
Meanwhile, Kona-Windows should now ignore Cntl-d and behave similar to k2.8

**Comment by kirbyfan64** [comment]
How about a slight derivation from k2? If two back quotes are used instead of one, all input is read like it currently is. I don't think that syntax even makes logical sense right now.

**Comment by kevinlawler** [comment]
The syntax idea in "0:\`" is that the empty symbol represents an unnamed, hence invalid, file. So you can do something else with the syntax. If you find another invalid syntax combination you could move the desired but incompatible functionality there. So for instance something like `0: 0` appears to be unused and could represent reading from file descriptor 0, which is stdin. This is one option. I don't know if it's the best.

**Comment by tavmem** [comment]
Regarding the additional difference:
in k2.8 (echo | k y):
```
tom@xps ~/k $ echo | k y
abc
def
  tom@xps ~/k $ 
```
In Kona-Linux/Unix (echo | k y):
```
tom@xps ~/kona $ echo | k y
abc
def
  tom@xps ~/kona $ 
```
in k2.8 (rlwrap ./k y)
```
tom@xps ~/k $ rlwrap k y
K Console - Enter \ for help

  abc
def
  \\
tom@xps ~/k $ 

```
In Kona (rlwrap ./k y)
```
tom@xps ~/kona $ rlwrap ./k y
K Console - Enter \ for help

  abc
def
  \\
tom@xps ~/kona $ 
```
Both give exactly the same results.
In all cases the 2 spaces come as a result of the k prompt (which is 2 spaces).
When you use "echo" the prompt comes at the end (note how the 2 spaces come before tom@xps)
When you use "rlwrap ./k y" the prompt comes first (the "abc" is indented).

There is no "additional difference".

**Comment by tavmem** [comment]
An alternate syntax (as suggested by Kevin) is certainly a possibility, but not a priority.
My immediate priority is consistency among platforms.
Going with the k2.8 strategy (for now).

The k-statements you provided may seem long, but they don't seem onerous.

**Comment by bakul** [comment]
How about another alternative?

Let ` have the same semantics as now. But if you use
`"/dev/stdin" or `"/dev/fd/0" it can read the whole file. This
is already the case for normal files and it should work for
any fifos and char devices. In particular I'd like
something like

    foo | bar | zee

to work where any of them can be a k script!

**Comment by bakul** [comment]
In fact, k works the same way as I suggested.  Try this:

    cat >kscript<<'EOF'
    #! env k
    x:0:`"/dev/fd/0"
    `0:x
    EOF
    chmod +x kscript
    ls|kscript

**Comment by kirbyfan64** [comment]
@tavmem I'm seeing a difference:

```
ryan@DevPC-LX:~/langtest/k$ cat y.k
`0:("abc";"def")
`0:"abc"
ryan@DevPC-LX:~/langtest/k$ echo | k y.k # Kona prints 2 spaces at the end
abc
def
abc  ryan@DevPC-LX:~/langtest/k$ 
ryan@DevPC-LX:~/langtest/k$ echo | k2 y.k # k2 prints no spaces at the end
abc
def
abc
ryan@DevPC-LX:~/langtest/k$ 
```

I accidentally copied only the first line of the test program.

**Comment by tavmem** [comment]
Interesting.
I tried it using k3.2 for Windows and got the following results:
```
~/k$ cat y.k
`0:("abc";"def")
`0:"abc"
~/k$ echo | k y
abc
def
abcK 3.2 2005-06-25 Copyright (C) 1993-2004 Kx Systems
WIN32 2CPU 4000MB inspiron.home 0 EVAL

~/k$
```
Here, I don't get the 2 spaces.
Instead, I get the K-banner, then a blank line.

Does your version of k3.x run on Windows, or on Linux?

**Comment by kirbyfan64** [comment]
I tried it with k2; I don't have a copy of k3. I'm on Linux.

**Comment by tavmem** [comment]
The 2 space prompt has been removed.  Now in Kona-Linux/Unix you should get:
```
~/k$ echo | k y
abc
def
abc
~/k$
```
