### ISSUE TITLE
Travis?

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#360]
This isn't for just CI. Travis allows uploading artifacts, so we (I?) could write up a few benchmark programs and run them in the test suite. Then the timings could be uploaded online. That way, performance changes can be tracked with every commit.

**Comment by tavmem** [comment]
I don't know anything about Travis.
In principle, I have no issue with the use of any tool that spots a degradation in performance.

**Comment by tavmem** [comment]
I don't typically use Cachegrind, other profilers, debuggers, or other automated tools.
If they help, that's great.

**Comment by kirbyfan64** [comment]
@tavmem Well, I don't use an IDE either (my "IDE" is Howl+Terminal+grep+sed). I figured this could be particularly nice for checking for performance regressions.

**Comment by tavmem** [comment]
Now that we resolved all identified build, crash, bug and feature issues, we are now in the optimization phase.    Nearly all the commits in this phase will be focused on speed improvements.  I'm not that concerned that a commit will produce a speed regression.  We also have a pretty good idea as to what needs to be addressed to get some speed improvements.  While Travis is one of several enhancement/optimization ideas, it's not an immediate priority for me.

**Comment by bakul** [comment]
What i was suggesting was to use gprof for profiling.
Basically build k like so:

  make CFLAGS+=-pg k

then execute a k expression you want to measure, quit
and run

  gprof k

You may have to modify or enhance your test to measure things
in more detail. Or run a test with different counts to factor
out common overhead.

gprof output will tell you which functions take how much time
and how often they were call and so on.  Then look at the top
few functions that take the most time.  This helps you focus
your effort where it may pay off the most.

gprof has a lot of options so it may be worth going through an
online tutorial or reading some related papers if you are not
familiar with it.

**Comment by tavmem** [comment]
Thanks.
I'll try it.

**Comment by kirbyfan64** [comment]
Considering that actual test-related regressions keep coming up, it might be worthwhile to do this anyway. Travis will run the tests for every PR and tell you before it's merged to prevent the issues that occurred (sorry...) from happening.

**Comment by tavmem** [comment]
In the 379 case, you did run the tests, saw 60 failures, but mistakenly thought that was OK.
In the 378 case, there was no test set up to catch the regression.
In the 312 case, again, there was no test set up to catch the regression.
Travis would not have helped in any of these cases.

**Comment by kirbyfan64** [comment]
> you did run the tests, saw 60 failures, but mistakenly thought that was OK

That makes it sound even worse... :O

**Comment by tavmem** [comment]
It's really not a big deal.  As I said, it was easily fixed.
It's just that I have limited time to spend on Kona, and Travis seems like extraneous overhead.
We already have a testing framework.  It works if the tests exist.
Working on a "better" solution is not a priority for me, though other people might love Travis.

**Comment by tavmem** [comment]
Addressed by @fenollp
