### ISSUE TITLE
`3: is not supposed to always block

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#364]
Example:

```
ryan@DevPC-LX:~/unc$ rlwrap k2
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
Evaluation. Not for commercial use. 
\ for help. \\ to exit.

  `3:"sleep 1" / this returns immediately
  `3:"sleep 1; echo 1" / this blocks
1
  
ryan@DevPC-LX:~/unc$ rlwrap k
K Console - Enter \ for help

  `3:"sleep 1" / this blocks
  `3:"sleep 1; echo 1" / as does this
1
  
ryan@DevPC-LX:~/unc$ 
```

**Comment by tavmem** [comment]
Why does it matter whether `3: always blocks, or not,
that is, other than strict compatiblity with k2.8?

**Comment by kirbyfan64** [comment]
@tavmem For me, it's the possibilities. You can launch a process but be detached from it. Python's `subprocess` module does that by default unless you explicitly request the command's output.

On the other hand, I'm curious on what K2's heuristic for determining if a command will print anything is.

**Comment by kirbyfan64** [comment]
@tavmem Ah, I think it's also to implement asynchronous message passing. Snippet from the K2 reference manual:

>  If the purpose is
to set a value, as it is for Remote Set, then the message is sent asynchronously. That
is, execution of t 3: x completes immediately, even though the message may
still be on its way or is still being evaluated in the other process.

**Comment by tavmem** [comment]
Thanks!

**Comment by tavmem** [comment]
In Kona (currently), both commands call "system(s)" for the (s)tring. So, Kona blocks in both cases.
The Linux man page:
>int system(const char *command);
system() executes a command specified in command by calling /bin/sh -c command, and returns after the command has been completed.

Seems like k2.8 must use something else, in order to block in one case, but return immediately in the other.

**Comment by tavmem** [comment]
On page 188 of kref:
>When t is ‘  then x is a character string holding an operating system command, and the effect of this function to have the command executed.

but, apparently, not with "system(s)".

**Comment by kirbyfan64** [comment]
@tavmem Likely `exec`, and explicitly passing the shell. I believe Python does that.

**Comment by tavmem** [comment]
Maybe ... maybe not ... exec seems to look for a file.
Linux man page for exec:
>The exec() family of functions replaces the current process image with a new process image.
The initial argument for these functions is the name of a file that is to be executed.

**Comment by kirbyfan64** [comment]
@tavmem I meant `execvp`. Oops. ;) Most languages use `fork` to fork the process and call `execvp` with the shell explicitly given, e.g.:

```c
void run(char* prog, char** argv, int argc) {
    if (fork() ==  0) {
        char args[argc+1];
        args[0] = prog;
        memcpy(args+1, argv, sizeof(char*)*argc);
        execvp("sh", args);
    }
}
```

**Comment by tavmem** [comment]
2 follow-up commits:

relax no-wait condition 1502d02291e003157d83a5cedec9491719b1dc6c

eliminate some redundant code 1d2871d24b9bc798a2fe72e461f86ee235356fd5
