### ISSUE TITLE
Difference in handling of 'atom

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#367]
I'm not quite sure what this is supposed to be, but:

K2:

```
ryan@DevPC-LX:~$ rlwrap k2
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
Evaluation. Not for commercial use. 
\ for help. \\ to exit.

  'x
value error
x
^
parse error
  '1

  '"a"
a
  '"abc"
abc
  '1 2 3

  
ryan@DevPC-LX:~$ 
```

Kona:

```
ryan@DevPC-LX:~$ rlwrap k
K Console - Enter \ for help

  'x
nyi error
>  \
  '1
nyi error
>  \
  '"a"
nyi error
>  \
  '"abc"
nyi error
>  \
  '1 2 3
nyi error
>  \
  
ryan@DevPC-LX:~$ 
```

I'm not sure if K2's behavior has any real-world use, though.

**Comment by tavmem** [comment]
The relevant feature here appears to be "Signal"
which is described on pages 173-175 of kref.

**Comment by kirbyfan64** [comment]
I want to try implementing this...

...but the source is a bit hard on the eyes... :O

So far, I know the error is raised at line 756 of kx.c. I'm guessing all that's needed to be done is check if the adverb is `'`, make sure the argument is a string, and return it via `kerr`?

**Comment by kirbyfan64** [comment]
Ack, this got messy quickly. The pointer `K* k` passed to `ex1` is `NULL`, and seems to be no way to get access to argument it was given. Argh...

**Comment by tavmem** [comment]
Re:
>I want to try implementing this...

OK ... I'll start working on issue 368.

**Comment by kirbyfan64** [comment]
@tavmem Ah, that was it! I couldn't figure out how to access the K object passed to the adverb.

**Comment by tavmem** [comment]
Yeah.  The key is to understand the data structures ... more so than the code.
Also, using the repositiory tavmem/konaStk helps
When executing
```
  '"abc"
```
this section gives you the clues you need:
```

C| Z K ex0(V*v, K k, I r)  kx.c  <-  ex_ 
     1st arg kW(x): 0xb777f5d8 0x9
       kW(x)[0]: 0x9
       kW(x)[1]: 0xb777f65c     0xbffe1be0 0xb777f600 1 -3 3   "abc"
       kW(x)[2]: (nil)
     2nd arg     y:      
     3rd arg     r: 0
D| K ex1(V*w, K k, I*i, I n, I f)  kx.c  <-  ex0  -- CS(0)
     1st arg v+1+i: 0xb777f5d8 0x9
     2nd arg     0: 0
     3rd arg    &i: 0xbffe1c48 -1
     4th arg     n: 2
     5th arg     1: 1
error msg set to 'nyi'
```

**Comment by tavmem** [comment]
Further explanation: You can see (above)

In the call to ex0() the 1st arg is kW(x)
which (from the wiki) is a "Void pointer to string in CODE of a type 7 object"
The full code structure is displayed

In the call to ex1() the 1st arg is a specific point in the CODE

**Comment by tavmem** [comment]
The "0x9" is an offset in DT (the Dispatch Table)
which is listed in src/k.c

**Comment by tavmem** [comment]
CODE is structured as a string so that it is easy to identify the end of CODE.
