### ISSUE TITLE
(\) 1 2 3

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#370]
In k2.8 and k3.2:
```
  (\) 1 2 3
1 2 3
1 2 3
```
in Kona:
```
  (\) 1 2 3
1 2 3
```
I could find no reference to this behavior of k2.8 and k3.2 in kref or in kusr.
Is this an unintentional behavior of k2.8 and k3.2 ... or a feature?

**Comment by tavmem** [comment]
It is probably best (at least for compatibility) if we treat this as an "undocumented feature".

**Comment by tavmem** [comment]
This turns out to be simply an instance of "Trace" which was not implemted in Kona.

in k2.8:
```
  (\) 1
1
1
  a:(\) 1
1
  a
1
```

**Comment by zzcworld** [comment]
@tavmem The help function (single backslash) does not work after this fix.

**Comment by tavmem** [comment]
Thanks!
