### ISSUE TITLE
(+)

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#372]
In k2.8 and k3.2
```
  (+)
+
  (+) 1
valence error
(+) 1
^
>  \
  (+) [1;2]
syntax error
(+) [1;2]
    ^
parse error
```
In Kona
```
  (+)
+
  (+) 1
+[1;]
  (+) [1;2]
3
```
Is this an intentional enhancement in Kona?

**Comment by kirbyfan64** [comment]
I personally *really* like this, and I doubt that any K2 scripts depend on this behavior.

**Comment by tavmem** [comment]
I agree that we should consider it a Kona enhancement, and leave it at that.
