### ISSUE TITLE
reference to parent function bug?

### ISSUE THREAD

**Issue by bakul** [kevinlawler/kona#377]
perm x creates all possible permutations of list x. This works fine in k but not kona
```
  p:{[n]:[1=#n;,n;{x,',/p[n _dv x]}'n]};
  perm:{,/p[x]};
  perm "ab"
stack error
{x@&(#y)=y?/:x}
  ^
```

**Comment by tavmem** [comment]
Somewhat interesting:
The Windows version of Kona does not yield "stack error", 
but it doesn't yield the correct result either.
```
  perm "ab"
"ab"
```

**Comment by tavmem** [comment]
This problem is also due to a regression.
The correct result is obtained when using the commit 5d8eda84343e7478b486968b85ea8e42337e6bf3 of Jan 27 2015.
Kona yields incorrect results after that date.
The regression occurred when fixing issue #288: Named Recursion.
