### ISSUE TITLE
(_2^31)-2147483647

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#387]
in k2.8 and k3.2
```
  (_2^31)-2147483647
0
```
in Kona
```
  (_2^31)-2147483647
1
```
in q
```
q)(floor 2 xexp 31)-2147483647
1
q)
```
This was most probably an intentional deviation in Kona away from k2/k3 and to agree with q
But Kona should agree with k2/k3.

**Comment by tavmem** [comment]
Kona should agree with k2/k3 except that
2^31 is equal to 2147483648.
Kona is incorrect here.

**Comment by bakul** [comment]
k3 does 32 bit arithmetic, so _2^31 will return 0I (integer
infinity). Even 2147483647 (2^31-1) is considered 0I. The
largest positive int is 2^31-2 == 2147483646. But then we
have anomalies like this:

```
  (_2^40)-1
2147483646
  x:_2^30
  x+x
0N
  _2^31
0I
  x:2147483646
  x+1
0I
  x+2
0N
  x+3
-0I
  x+4
-2147483646
```

The concept of integer infinity has not been carried far enough!

kona uses 64 bit arithmetic. It is broken near the limits in a
different way!


```
  x:_2^62-2
4611686018427387904
  x+x
-9223372036854775808
  _2^63
0N
```

Given that things are broken somewhat near the limits in k3 as well,
I believe we should just note this difference and not "fix it" as
most fixes will be partial, unless you actually use 32 bit ints.

BTW, the latest kona is broken on FreeBSD:
src/bswap.c:9:27: error: bits/byteswap.h: No such file or directory

**Comment by tavmem** [comment]
Thanks!

**Comment by tavmem** [comment]
Kona does compile on 32 bit, and is used on 32 bit machines.
My primary Linux box is 32 bit.
We have Android users, and QNAP users.

Currently, when compiling Kona on a 32 bit machine
```
  (_2^31)
2147483648
  (_2^32)
4294967296
```
Are you saying we should purposely give incorrect results, just to maintain consistency with k2/k3?

**Comment by bakul** [comment]
On Sun, 25 Oct 2015 20:11:24 PDT Tom Szczesny <notifications@github.com> wrote:
> 
> Are you saying we should purposely give incorrect results, just to maintain c
> onsistency with k2/k3?

Kona uses 64 bit integers even on 32 bit word size machines.
Its current behavior is not consistent with k2/k3 for ints >=
2^31. I am saying this is fine. Just document the behavior.
There should be a "differences from k2/k3" file for this.

**Comment by tavmem** [comment]
I agree.

**Comment by tavmem** [comment]
@pahihu wrote:

On Linux 64bit this test fails:
```
Failed. These are not equal:
0 , 0I-2147483647
********************************
0
--------------------------------
9223372034707292160
```

**Comment by tavmem** [comment]
This test only works on 32-bit machines, and should be removed.

But, since Kona uses 64 bit integers, why should this test work on a 32-bit machine?
The setting for 0I on 32-bit machines may be inappropriate.

**Comment by tavmem** [comment]
@pahihu wrote:
```
Contrary on Windows with 64bit Kona:

  (-1)+_2^31
0I

  0I-(-1)+_2^31
0
```

**Comment by tavmem** [comment]
@pahihu wrote:
```
The culprit is the definition of II and IN in ts.h:

#define II LONG_MAX
#define IN LONG_MIN

This is 32-bit on Windows, even when using a 64bit compiler,
and generally 64bit on UN*X.

These should be:

#define II LONG_LONG_MAX
#define IN LONG_LONG_MIN
```

**Comment by tavmem** [comment]
@pahihu wrote:
```
And in kg.c the floating-point compare fn FC() should be changed
to use LLONG_MAX/LLONG_MIN.

I checked the LONG_LONG_MAX/LONG_LONG_MIN constants and these
are Windows specific. Use LLONG_MAX/LLONG_MIN instead.
```
