### ISSUE TITLE
Segmentation fault / Debian linux 3.2.0-4

### ISSUE THREAD

**Issue by marvinmarvin22** [kevinlawler/kona#390]
Hi,
I just started learning K, so I thought had committed an error too stupid to be caught. But the windows version does not have the problem, so it might be an error in the linuxversion

What i typed in was:

 c: 1 4 3 0.5 -2
 mdev:{x-(+/x)%#x}
 fo:{+/ _sqr  mdev x}

 mdev c
-0.3 2.7 1.7 -0.8 -3.3
fo c
Segmentation fault

On Windows I get a normal 21.8
gdb:
Program received signal SIGSEGV
0x000000000041c237 in ex2 (v=v@entry=0x7ffff7ff8fa0, k=k@entry=0x0)
at src/kx.c:954
954	&& (*(K*)kS(kK(prnt)[CACHE_WD])[CODE][0])->t==7

uname -a
Linux ... 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1 x86_64
running in xterm.

What is a starting point to look for to fix this?
cheers

**Comment by marvinmarvin22** [comment]
UPDATE
===
As i said, I am just starting to learn K.
I found that the following versions of fo do work:
fo:{+/ _sqr (temp:mdev x)}
and
fo:{+/ _sqr (x-(+/x)%#x)}
I should either use a temporary variable to catch the result of the home made function mdev, or i should substitute the mdev function by its definition. Both solutions work fine on Linux.
Remaining point for me is that the definition fo:{+/ _sqr mdev x} is much shorter and clearer than the two correct definitions above. Also, it does work on windows: K does not work the same on Windows (running in powershell) as it does on Debian (running in xterm)

**Comment by tavmem** [comment]
Kona also segfaults under Gentoo/Linux.
```
  c: 1 4 3 0.5 -2
1 4 3 0.5 -2.0
  mdev:{x-(+/x)%#x}
{x-(+/x)%#x}
  fo:{+/ _sqr mdev x}
{+/ _sqr mdev x}
  mdev c
-0.3 2.7 1.7 -0.8 -3.3
  fo c
rlwrap: warning: k killed by SIGSEGV.
```

**Comment by tavmem** [comment]
This is a regression error.  Using the Kona commit 34eebbf279d1d7325a2ba2fab0f50ecf8b084073
of Oct 15, 2015, I get
```
  c: 1 4 3 0.5 -2
1 4 3 0.5 -2.0
  mdev c
1 4 3 0.5 -2.0
  mdev:{x-(+/x)%#x}
{x-(+/x)%#x}
  mdev c
-0.3 2.7 1.7 -0.8 -3.3
  fo:{+/ _sqr mdev x}
{+/ _sqr mdev x}
  fo c
21.8
```

**Comment by tavmem** [comment]
The commit that caused the regression is  8f31453b564306447b88e669211efdb66019d1f7
done on Nov 8, 2015 and titled "partial fix for issue 388"
