### ISSUE TITLE
inconsistent behaviour "type error"

### ISSUE THREAD

**Issue by marvinmarvin22** [kevinlawler/kona#391]
Hi,

It might be due to my limited k-knowledge, but I have a function which runs once and then keeps on  giving a 'type error' :
I have typed in this, right after starting K:
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]}
  am:{(+/x)%#x}
  p: 1 4 6 7 8
  km:{ am x [ mi (# x)] }
  km p
6
  km p
type error
>

 and, next just
  mi (# p)
type error
>
  but still:
  am p
5
- -  - - 
My km-function works just once, and than locks up giving just type errors. From that point on, the mi function used in it, also returns type error. 

The function body in itself works fine:
After restart:
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]}
  am:{(+/x)%#x}
  p: 1 4 6 7 8
  am p [ mi (# p)]
6
  mi (# p)
2
  mi (# p)
2
  mi (# p)
2
  am p [ mi (# p)]
6
// etc etc etc .. but just once:
  km:{ am x [ mi (# x)] }
{ am x [ mi (# x)] }
  km p
type error
>
  km ( 2 3 4)
type error

-- --- 
Have I defined an illegal function here ?The errors on the windows and linuxversions are the same.
It does not help ifI explicitly define the bound variables, or use different letters for all of them.

Cheers
mm

**Comment by kirbyfan64** [comment]
Once the `>` appears, you're in an error mode. Try entering a slash `\` in order to exit.

**Comment by marvinmarvin22** [comment]
mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]}
{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]}
  am:{(+/x)%#x}
{(+/x)%#x}
  am:{(+/x)%#x}
{(+/x)%#x}
  p: 1 4 6 7 8
1 4 6 7 8
  km:{ am x [ mi (# x)] }
{ am x [ mi (# x)] }
  km p
6
  km p
type error
>  \
  km p
type error
>  \
  km p
type error
>  \
  km p
type error
>

**Comment by tavmem** [comment]
A simpler path to producing a similar error:
```
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]};
  {mi x}5
2
  {mi x}5
type error
>
```

**Comment by tavmem** [comment]
This is a regression error.
Using the commit 916c097275a37e1fd5bbd5b5ecbe00d9db9666a0 dated 12/29/13 titled "cosmetics"
```
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]};
  {mi x}5
2
  {mi x}5
2
```
Using the commit d66897c23a79a6f9c916d6122b04e20584a11b6b dated 12/30/13 titled "fix 221 -- (3rd attempt)"
```
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]};
  {mi x}5
2
  {mi x}5
type error
```

**Comment by tavmem** [comment]
An simpler case that produces "type error":
```
  m:{:[x!2; 1; 2]};
  {m x}5
1
  {m x}5
type error
>  
```
An even simpler case that causes a segfault:
```
  m:{:[x; 1; 2]};
  {m x}5
1
  {m x}5
rlwrap: warning: k killed by SIGSEGV.
```

**Comment by tavmem** [comment]
The above commit fixes the 3 simpler cases, but not the original reported problem:
```
  mi:{:[x!2;(x-1)%2; _ ((x-1),x)%2.0]};
  {mi x}5
2
  {mi x}5
2

  m:{:[x!2; 1; 2]};
  {m x}5
1
  {m x}5
1

  m:{:[x; 1; 2]};
  {m x}5
1
  {m x}5
1
```

**Comment by lorean-lorean** [comment]
Hi
It is because you used variable "x". Without it, it crashes:
 m:{:[x; 1; 2]};
{m 3} 5 
{m 3} 5 
crashes on my linux system
(gdb) print prnt
$6 = (K) 0x7ffff7ff4080
(gdb) print z->t
Cannot access memory at address 0x8
all prints v[1]:
0x3c
0x1
0x7ffff7ff8be0
0x0
0x7ffff7ff8ee0
0x0
0x0
0x1
0x1
0x7ffff7ff8ba0
0x0
0x7ffff7ff3060
0x0
0x0
0x1
Program received signal SIGSEGV, Segmentation fault.
0x000000000041b38e in ex2 (v=v@entry=0x7ffff7ff4518, k=k@entry=0x0)
    at src/kx.c:912
912         if(prnt && z->t==7) {
v[1]:0x1

**Comment by tavmem** [comment]
Thanks !

**Comment by tavmem** [comment]
After the last commit:
```
  m:{:[x; 1; 2]};
  {m 3}5
1
  {m 3}5
1
```

**Comment by lorean-lorean** [comment]
Hi,
I went through the e0-e_-e1-e2's, the second time around there is indeed a object of zeros. 
In the meantime i saw this.
e:2 2 # 2.1 4.008 3 0.3
(2.1 4.008
 3 0.3)
  _inv e
(-0.02632965 0.3517641
 0.2632965 -0.1843075)
  e _lsq e
(1 1.110223e-16
 4.440892e-16 1.0)
  e _mul e
Nothing is returned in the multiplication.
I know that K is not Q, but in Q i have
q)e:2 2 # 2.1 4.008 3 03
q)e
2.1 4.008
3   3    
q)inv e
-0.524109 0.7002096 
0.524109  -0.3668763
q)e mmu e
16.434 20.4408
15.3   21.024 
is this a related problem, or do I use the _mul the wrong way

**Comment by lorean-lorean** [comment]
Hi
I do not know if it is related, but in the current version nothing seems to be returned from _mul.

e:2 2 # 2.1 4.008 3 0.3
(2.1 4.008
 3 0.3)
  _inv e
(-0.02632965 0.3517641
 0.2632965 -0.1843075)
  e _lsq e
(1 1.110223e-16
 4.440892e-16 1.0)
  e _mul e
In Q I do get output
q)e:2 2 # 2.1 4.008 3 0.3
q)inv e
-0.02632965 0.3517641 
0.2632965   -0.1843075
q)e mmu e
16.434 9.6192
7.2    12.114
but, of course, the rule for using _mul might be different than the one for mmu

**Comment by tavmem** [comment]
The above commit fixes the original problem for this issue.
I have not looked at _mul yet.
If it is a bug, I will open a separate new issue.
