### ISSUE TITLE
_mul

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#392]
@lorean-lorean wrote:
```
Hi
I do not know if it is related, but in the current version nothing seems to be 
returned from _mul when applied to two matrices

e:2 2 # 2.1 4.008 3 0.3
(2.1 4.008
3 0.3)
_inv e
(-0.02632965 0.3517641
0.2632965 -0.1843075)
e _lsq e
(1 1.110223e-16
4.440892e-16 1.0)
e _mul e
In Q I do get output
q)e:2 2 # 2.1 4.008 3 0.3
q)inv e
-0.02632965 0.3517641 
0.2632965 -0.1843075
q)e mmu e
16.434 9.6192
7.2 12.114
Of course, the rule for using _mul might be different than the one for mmu.

It looks like _mul works like { x*+/x} if x is a list

p:{ x[;0]+/x[;0]}
{ x[;0]+/x[;0]}
p e
10.71 15.3
e[;0] _mul e[;0]
10.71 15.3
for
e
(2.1 4.008
3 0.3)
```

**Comment by tavmem** [comment]
In k2.8
```
  e:2 2 # 2.1 4.008 3 0.3;
  _inv e
(-0.02632965 0.3517641
 0.2632965 -0.1843075)
  e _lsq e
(1 1.321384e-16
 0 1.0)
  e _mul e
(16.434 9.6192
 7.2 12.114)
```
BTW: You can get a copy of k2.8 (which is 32-bit).  See
https://groups.google.com/forum/#!topic/kona-dev/FmKodC-geac

**Comment by lorean-lorean** [comment]
Hi,

thanks for that tip.

Maybe the _mul is a straight K-application ? When I force an error, I get
  e _mul w
type error
{x _dot\:y}

But the matrix multiplication in K should be like   {x _dot/:\: +x}e   

The function in the type error messages gives the same values as the current, broken, _mul

current K-version:
 e
(1 8.2
 5 3.2)
  {x _dot\:y}[e;+e]
  {x _dot\:y}[e[0;];+e[0;]]
9.2 75.44
  e _mul e
  e[0;] _mul e[0;]
9.2 75.44

The correct function is  {x _dot/:\: +x}
{x _dot/:\: +x} e
(42 34.44
 21 51.24)
or
 {x _dot/:\: y}[e;+e]
(42 34.44
 21 51.24)

**Comment by tavmem** [comment]
This is a regression error.  Using the commit 330945a86a0abaf1df6c0301bd7c52b4c8f6edf1 of Dec 20, 2015, titled "fix #390: Segmentation fault", Kona yields:
```
  e:2 2 # 2.1 4.008 3 0.3; e _mul e
(16.434 9.6192
 7.2 12.114)
```
Using commit 508b67cf975f51da416c211ece2674ab7c498168 of Dec 22, 2015, titled "merge pahihu  thru Dec 22", Kona yields null:
```
  e:2 2 # 2.1 4.008 3 0.3; e _mul e
  
```

**Comment by tavmem** [comment]
@lorean-lorean wrote:
> Maybe the _mul is a straight K-application ?

There are number of features that implemented in k code that have cover functions for ease of use.  You can find most of them in the file src/r.c

Try searching in src/r.c for "mul" or for "ssr".

**Comment by lorean-lorean** [comment]
Indeed :)
with a patch on r.c
97c97
< S_DYAD(mul,  "{x _dot/:\\:+y}") 
---
> S_DYAD(mul,  "{x _dot\\:y}") 

i get

e: 2 2 # 2 8 7. 1
 f: 2 3 # 2. 3 1 2 2.5 1.5
_mul [e;f]
(20 26 14.0
 16 23.5 8.5)
 e _mul f
(20 26 14.0
 16 23.5 8.5)
 (+f) _mul e
(18 18.0
 23.5 26.5
 12.5 9.5)

**Comment by tavmem** [comment]
Oops.
After the executing the pull request, there are 2 tests that now fail.

**Comment by tavmem** [comment]
@pahihu re-implemented _dot to make it faster.
However, that caused the error documented by @lorean-lorean in this issue.
@lorean-lorean implemented a patch to fix this issue.
However, that patch caused 2 other tests to fail.
I backed out the patch from @lorean-lorean and the optimization from @pahihu & added a test.
The optimization can be re-implemented when all tests work.

**Comment by lorean-lorean** [comment]
Oops indeed; so it was not as simple as just substituting the function in the r.c file
p:{x _dot/:\:+y}
  p[ 10 10; 20 20 ]
(200 200
 200 200)
 _mul[ 10 10 ; 20 20 ]
400 400

**Comment by pahihu** [comment]
I have fixed the matrix multiplication bug: I have used the plus_over() fn in k.c which does not handle
the generic list case. Now works as expected.

But in K3.2:
     10 10 _mul 20 20
400 400

K is not Q ;)
