### ISSUE TITLE
How about a logo for this project?

### ISSUE THREAD

**Issue by rtoal** [kevinlawler/kona#395]
Just a nice to have....

**Comment by thyrgle** [comment]
I've been busy with work recently, but I did work on this website for Kona a while back: 
http://kona.github.io/#/
(Git repo: https://github.com/kona/kona.github.io)

There is a possible logo on that. Maybe it should be added to the README though...

**Comment by rtoal** [comment]
Nice page. Funny that it does not show up on the first page of a Google search (for kona language). Would Kevin have the final say for the logo?

**Comment by kirbyfan64** [comment]
Nice site, BUT the logo goes half off the page on Android..

**Comment by thyrgle** [comment]
@rtoal: Thanks!

@kirbyfan64 Yeah, I never got around to making a mobile version. I don't think I had a smart phone at the time I made the website which made it hard to test a mobile layout.

**Comment by tavmem** [comment]
Sounds like we have a logo ... but need to get it to work on mobile.
