### ISSUE TITLE
function within function crashes

### ISSUE THREAD

**Issue by dlorean00004** [kevinlawler/kona#396]
Hi,

My functions may not be proper K, but in the 2013 and kona-916c097275a37e1fd5bbd5b5ecbe00d9db9666a0 K-versions and in K2.8, the code
 idm:{(2# x) # 1.,x # 0.0}
 fct:{(+%': +x)[;!(-1+#x)]}
 tfct:{ +/ (fct (+\ x))[ !-1+#x;] * |idm (-1+#x)}
 M: 3 3 # 2. 3 1 2 2.5 0 4 0 0
 tfct M
returns
 1.375 0.3333333

In the Dec 30 version the tfct-function causes a segmentation fault

The function body itself does return:
 +/ (fct (+\ M))[ !-1+#M;] * |idm (-1+#M) 
 1.375 0.3333333

note:
I tried to simplify this to: 
 fct:{x}
 tfct:{ (fct x)[!2;]}
This crashes, but that crash is solved by using square brackets for the function argument
 fct:{x}
 tfct:{ (fct[x])[!2;]}
(2 3 1.0
 2 2.5 0.0)
Using brackets in the complete tfct function above does not help, however.

0x000000000041c137 in ex2 (v=v@entry=0x7ffff7ff4440, k=k@entry=0x0) at src/kx.c:1012
1012                  && !kV(kK(kK(kK(kK(prnt)[CACHE_WD])[LOCALS])[0])[1])[CONJ] ) {
#0  0x000000000041c137 in ex2 (v=v@entry=0x7ffff7ff4440, k=k@entry=0x0) at src/kx.c:1012
#1  0x000000000041b639 in ex2 (k=0x0, v=0x7ffff7ff4440) at src/kx.c:890

**Comment by dlorean00004** [comment]
Hi,

thanks to your tip I am now able to compare results to K2.8. I am not sure if this is related to the above, but the following function works on K2.8. In kona I get a type error when calling the function, but when I run all its statements globally, I get the expected result.
getcsvFloat:{[filename;separator]
f: { x@ & (#:' x) >0 }[ 0:filename ] ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];(*|x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing  replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\:[f;separator] ;
}
K2.8 :
  getcsvFloat["testfile";";"]
(200 20.02 300 0 0 0
 40 50 10 0 0 0.0)
  \cat testfile
200;20.02;300;;0;
40;50;10;;;

Kona:
  getcsvFloat["testfile";";"]
type error

**Comment by tavmem** [comment]
The first problem has been fixed, but not the second.
Will open a separate issue.
