### ISSUE TITLE
getcsvFloat

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#397]
@dlorean00004 wrote:

Hi,

thanks to your tip I am now able to compare results to K2.8. I am not sure if this is related to the above, but the following function works on K2.8. In kona I get a type error when calling the function, but when I run all its statements globally, I get the expected result.
getcsvFloat:{[filename;separator]
f: { x@ & (#:' x) >0 }[ 0:filename ] ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing  replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\\:[f;separator] ;
}
K2.8 :
  getcsvFloat\["testfile";";"]
(200 20.02 300 0 0 0
 40 50 10 0 0 0.0)
  \cat testfile
200;20.02;300;;0;
40;50;10;;;

Kona:
  getcsvFloat["testfile";";"]
type error

I think this can be reduced to:
getcsvFloat:{
f:  "200,20.02,0,8,9,0"  ;
conv:{ . ": ",x} ;
conv[f] 
}

  r:getcsvFloat[]
type error
. ": ",x
\> \
 f:  "200,20.02,0,8,9,0"  ;
  conv:{ . ": ",x} ;
  conv\[f] 
(200;20.02;0;8;9;0)

**Comment by tavmem** [comment]
Further simplification. In Kona, this works:
```
  c:{ . ": ",x};c "200,20.02"
(200;20.02)
```
This does not:
```
  {c:{ . ": ",x};c "200,20.02"}0
type error
```

**Comment by dlorean00004** [comment]
Also:
 testf: {
\>  r: ( 30;40) ;
\>  : r[0]
\>  }
 testf[]
0
testf: {
\>  : ( 30;40)[0]
\>  }
testf[]
0

**Comment by tavmem** [comment]
This case has a minimal difference in syntax structue.  In Kona, this works:
```
  {c:{. x};c x}"9"
9
```
This fails:
```
  {c:{. x};c "9"}0
.[;]
```

**Comment by tavmem** [comment]
Commit 27e33992c4068f0966fb77134d9dc2ec37cc226b fixes the case
```
  {c:{. x};c "9"}0
9
```
but not the original problem identifed in this issue.

**Comment by tavmem** [comment]
In Kona, you can remove the braces to simplify the problematic case of {:(30;40)@0}0
```
  (30;40)@0
30

  :(30;40)@0
type error
```

**Comment by tavmem** [comment]
More corner cases (in Kona):
```
  :(3 4)@0
3
  :(3;4)@0
type error
```

**Comment by tavmem** [comment]
Commit 3a8f37964b18e2e7a6883c2420cc82ce45670e79 fixes the cases:
```
  {:(30;40)@0}0
30
  :(3;4)@0
3

```
but still, not the original problem.

**Comment by tavmem** [comment]
Commit 1f480fccd4dc47e1a5a59cee9ca8e1a0b1340fa9 corrects the following:
```
  @(+;-)
0
  @(+;-)
0
  0 5 9[(:10;:20);(:30;:40)]
40
  @(+;-)
1
```

**Comment by tavmem** [comment]
The first inconsistency I found was in the handling of "each" (and "each left").  Given 2 scripts:
```
  \cat gcsvf0.k
gcf:{[fname;sprtr]
 f:{x@&(#:'x)>0}[0:fname];
 rep:{_ssr[x;y;","]};
 rep'[f;";"]}
  
  \cat gcsvf1.k
gcf:{[fname;sprtr]
 f:{x@&(#:'x)>0}[0:fname];
 rep:{_ssr[x;y;","]};
 ctf:{[fn;sep]rep[fn;sep]};
 ctf'[f;";"]}
  ```
In k2.8 both give the same result:
```
  \l gcsvf0
  gcf["testfile";";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  \l gcsvf1
  gcf["testfile";";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
```
In Kona, they give different results:
```
  \l gcsvf0
  gcf["testfile";";"]
("200,20.02,300,,0,"
 "40,50,10,,,")

  \l gcsvf1
  gcf["testfile";";"]
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))
```

**Comment by tavmem** [comment]
Here is a surprise! 
The above suggested a problem with "each".  That may not be the case. Consider the following:
```
a0:{[f;s] \t:{x@&(#:'x)>0}[0:f];               r:{_ssr[x;y;","]}; r'[t;";"]}
a1:{[f;s] \t:{x@&(#:'x)>0}[0:f];               r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}
b0:{[f;s] \t:("200;20.02;300;;0;";"40;50;;;"); r:{_ssr[x;y;","]}; r'[t;";"]}
b1:{[f;s] \t:("200;20.02;300;;0;";"40;50;;;"); r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}
```
In k2.8, all 4 functions produce the same correct result.  In Kona, the a1 result is wrong, but b1 is correct!
```
a0["testfile";";"]
("200;20.02;300;;0;"
 "40;50;10;;;")
("200,20.02,300,,0,"
 "40,50,10,,,")

a1["testfile";";"]
  ("200;20.02;300;;0;"
 "40;50;10;;;")
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))

b0["testfile";";"]
  ("200;20.02;300;;0;"
 "40;50;10;;;")
("200,20.02,300,,0,"
 "40,50,10,,,")

b1["testfile";";"]
  ("200;20.02;300;;0;"
 "40;50;10;;;")
("200,20.02,300,,0,"
 "40,50,10,,,")
```
The only difference between a1 & b1 is that in a1 the text is read from "testfile" into t.
t is displayed by both functions, and looks identical in the display result of a1 and b1.
But t must be different in each case, or the final result of a1 & b1 should be the same.

It now seems that there may be a problem with 0: 
that does not show up in the display of the result of 0:
Sounds unlikely, but that is what this exercise indicates !

**Comment by tavmem** [comment]
The problem is not in 0:
Consider
```
a1:{[f;s] \t:{x@&(#:'x)>0}[0:f]; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}
c1:{[f;s] \t:0:f;                r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}

  a1["testfile";";"]
("200;20.02;300;;0;"
 "40;50;10;;;")
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))

  c1["testfile";";"]
("200;20.02;300;;0;"
 "40;50;10;;;")
("200,20.02,300,,0,"
 "40,50,10,,,")
```
{x@&(#:'x)>0} is transforming the result from 0:f and causing the problem in Kona.
But it does not cause a problem in k2.8.

**Comment by tavmem** [comment]
It's none of the above.  It's a "transient" problem re locals within a single function. In Kona:
```
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))
  
  t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
```

**Comment by tavmem** [comment]
The crux of the problem appears to be that locals get added to the KTREE in Kona.
In k2.8:
```
  .`
.((`k;;)
  (`t;-599096325;))

  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k;;)
  (`t;-599096479;))
```
In Kona
```
  .`
.((`k;;)
  (`t;-5.990962e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;;)
     (`t;;)
     (`s;;))
   )
  (`t;-5.990962e+08;))
  
    t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;{_ssr[x;y;","]};)
     (`t
      ("200;20.02;300;;0;"
       "40;50;10;;;")
      )
     (`s;;)
     (`c;{[t;s]r[t;s]};)
     (`z;;))
   )
  (`t;-5.990962e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;{_ssr[x;y;","]};)
     (`t
      ("200;20.02;300;;0;"
       "40;50;10;;;")
      )
     (`s;;)
     (`c;{[t;s]r[t;s]};)
     (`z;;))
   )
  (`t;-5.990962e+08;))
```

**Comment by tavmem** [comment]
This is related to issue #383: Referencing undefined variables should be an error.
Currently, undefined variables are also added to the KTREE.
In  Kona:
```
  .`
.((`k;;)
  (`t;-5.990957e+08;))
  
  a
  
  .`
.((`k
   .,(`a;;)
   )
  (`t;-5.990957e+08;))
```

**Comment by tavmem** [comment]
Further demonstration of the problem cause:
```
  .`
.((`k;;)
  (`t;-5.990948e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;;)
     (`t;;)
     (`s;;))
   )
  (`t;-5.990948e+08;))
  
  t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;{_ssr[x;y;","]};)
     (`t
      ("200;20.02;300;;0;"
       "40;50;10;;;")
      )
     (`s;;)
     (`c;{[t;s]r[t;s]};)
     (`z;;))
   )
  (`t;-5.990948e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;{_ssr[x;y;","]};)
     (`t
      ("200;20.02;300;;0;"
       "40;50;10;;;")
      )
     (`s;;)
     (`c;{[t;s]r[t;s]};)
     (`z;;))
   )
  (`t;-5.990948e+08;))
  
  .k: .k _di `x`y`r`t`s`c`z
.()
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))

```

**Comment by tavmem** [comment]
On the other hand ...
When .k is empty, that is when you would expect it to work properly.
The locals/globals/KTREE are probably getting tangled in this situation.

**Comment by tavmem** [comment]
Seems that "r" is the variable that is central to the problem:
```
  .`
.((`k;;)
  (`t;-5.990924e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";")
 ("40;50;10;;;"
  ";"))
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;;)
     (`t;;)
     (`s;;))
   )
  (`t;-5.990924e+08;))
  
  r:{_ssr[x;y;","]};
  
  {t:0:"testfile"; r:{_ssr[x;y;","]}; c:{[t;s]r[t;s]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
  
  .`
.((`k
   .((`x;;)
     (`y;;)
     (`r;{_ssr[x;y;","]};)
     (`t;;)
     (`s;;)
     (`z;;))
   )
  (`t;-5.990924e+08;))
```

**Comment by tavmem** [comment]
Note what happens when r is not defined as a projection of _ssr:
```
  .`
.((`k;;)
  (`t;-5.990919e+08;))
  
  {t:0:"testfile"; r:{_ssr[x;y;z]}; c:{[t;s]r[t;s;","]}; c'[t;";"]}0
(("200;20.02;300;;0;"
  ";"
  ",")
 ("40;50;10;;;"
  ";"
  ","))
  
    r:{_ssr[x;y;z]};
  
  {t:0:"testfile"; r:{_ssr[x;y;z]}; c:{[t;s]r[t;s;","]}; c'[t;";"]}0
("200,20.02,300,,0,"
 "40,50,10,,,")
```

**Comment by tavmem** [comment]
Seems that in the current state of Kona, when defining a function, it is
- OK to define local variables.
- OK to define lambdas
- RISKY to define named local functions within the function (Should be avoided.)

It's not how k2.8 works, but you can get the correct results you when using these rules.
```
  .`
.((`k;;)
  (`t;-5.990904e+08;))
  
  foo:{[fname;sep]t:0:fname; {[t;s] _ssr[t;s;","]}'[t;sep]};
  
  foo["testfile";";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
```

**Comment by tavmem** [comment]
The script at the start of this issue works in k2.8, and should work in Kona, but it doesn't.
Often, you can modifiy a problematic script somewhat and get correct results in Kona.
Obviously, the goal is that any script that works in k2.8 should work in Kona (except for k2.8 bugs).
Here is a modification of the initial script that does work in Kona:
```
  \cat gcf.k
gcf:{[f;s] /GetCsvFloat[filename;separator]
 gar:{[f;s] t:0:f; r:{_ssr[x;y;","]}; r'[t;";"]}; /GetAndReplace
 addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]};
 insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s};
 d:insertmissing'addmissing'gar[f;s];
 i:0; do[#d; d[i]:1.*. d[i]; i+:1]; /CharToFloat        
 d}

  gcf["testfile";";"]
((200.0;20.02;300.0;0.0;0.0;0.0)
 40 50 10 0 0 0.0)
```
In k2.8, (when using the gcf.k script) the first line of the result gets formatted better:
```
  gcf["testfile";";"]
(200 20.02 300 0 0 0
 40 50 10 0 0 0.0)
```

**Comment by tavmem** [comment]
Here is a script with very minor changes to the original that works in both k2.8 and Kona.
Original (run in Kona):
```
  \cat original.k
getcsvFloat:{[filename;separator]
f: { x@ & (#:' x) >0 }[ 0:filename ] ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\:[f;separator] ;
}
  getcsvFloat["testfile";";"]
type error
```
Revised (run in Kona, works also in k2.8):
```
  \cat revised.k
getcsvFloat:{[filename;separator]
f:0:filename ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
{1. *' x }' ChartoFloat\:[f;separator]}

  getcsvFloat["testfile";";"]
(200 20.02 300 0 0 0.0
 40 50 10 0 0 0.0)
```
Changes:
```
$ diff original.k revised.k
2c2
< f: { x@ & (#:' x) >0 }[ 0:filename ] ;
---
> f:0:filename ;
7,8c7
< :{1. *' x }' ChartoFloat\:[f;separator] ;
< }
---
> {1. *' x }' ChartoFloat\:[f;separator]}
```

**Comment by tavmem** [comment]
Seems that there are 2 remaining questions on this issue:
1) Why does {x@&(#:'x)>0} in line 2 of the original cause a problem?
2) Why does the early return (:) in line 7 of the original cause a problem?

**Comment by tavmem** [comment]
Regarding the Early Return: 
The Early Return token is being recognized too soon (before the calculation in line 7 is complete).
{1. *' x} applied to x when x is still text results in a type error.
Making a further revision, but still using Early Return:
```
  \l revised1.k
{[filename;separator]
f:0:filename ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
d:{1. *' x }' ChartoFloat\:[f;separator] ;
:d;
} 
  getcsvFloat["testfile";";"]
(200 20.02 300 0 0 0.0
 40 50 10 0 0 0.0)
```
yields the correct result.

**Comment by tavmem** [comment]
This comment documents what appears to the the problem with Early Return.
Revised script with original placement of Early Return and display of x value.
```
  \cat revised1.k
getcsvFloat:{[filename;separator]
f:0:filename ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
:{1. *' \x }' ChartoFloat\:[f;separator] ;
}
  getcsvFloat["testfile";";"]
("200;20.02;300;;0;"
 "40;50;10;;;")
type error
1. *' \x 
   ^
> 
```
Note that x is a list of 2 char stings each being multiplied by the 1. float.

**Comment by tavmem** [comment]
Commit be81cea829a541f0ba184e7fee9a122f84b5227c fixes the Early Return problem.
```
  \cat revised2.k
getcsvFloat:{[filename;separator]
f:0:filename ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\:[f;separator] ;
}
  getcsvFloat["testfile";";"]
(200 20.02 300 0 0 0.0
 40 50 10 0 0 0.0)
```
The final remaining open question in this issue is:
1) Why does {x@&(#:'x)>0} in line 2 of the original script cause a problem?

**Comment by tavmem** [comment]
Here are 2 simple scripts that show a problem caused by {x@&(#:'x)>0}
sim0.k works
```
 \cat sim0.k
gcf:{[fn;sp]
 t:0:fn;
 rep:{_ssr[x;y;","]};
 ctf:{[t;sp]rep[t;sp]};
 ctf'[t;sp]}

  gcf["testfile";";"]
("200,20.02,300,,0,"
 "40,50,10,,,")
```
sim1.k fails
```
  \cat sim1.k
gcf:{[fn;sp]
 t:{x@&(#:'x)>0}[0:fn];
 rep:{_ssr[x;y;","]};
 ctf:{[t;sp]rep[t;sp]};
 ctf'[t;sep]}

  gcf["testfile";";"]
(("200;20.02;300;;0;"
  )
 ("40;50;10;;;"
  ))
```

**Comment by tavmem** [comment]
Well, here is a BIG surpise:
Script sim1.k also fails in k2.8 (script sim0.k works in k2.8)
```
  \cat sim1.k
gcf:{[fn;sp]
 t:{x@&(#:'x)>0}[0:fn];
 rep:{_ssr[x;y;","]};
 ctf:{[t;sp]rep[t;sp]};
 ctf'[t;sep]}

  gcf["testfile";";"]
type error
{if[_n~x;:_n];i:1+2*!_.5*#x:(0,/(0,+/~+\(>':0,"["=y)-<':("]"=y$:),0)+/:x _ss y)_ x;,/ :[7=4:z;@[x;i;z];4:z$:;@[x;i;:[;z]];@[x;i;:;z]]}
                                                                         ^
> 
```

**Comment by tavmem** [comment]
This comment documents that the the text in testfile is unchanged in k2.8 by {x@&(#:'x)>0}
The script sim2.k is modified to display the contents of t
```
  0:"testfile"
("200;20.02;300;;0;"
 "40;50;10;;;")
  
  \l sim2.k
  \cat sim2.k
gcf:{[fn;sp]
 \t:{x@&(#:'x)>0}[0:fn];
 rep:{_ssr[x;y;","]};
 ctf:{[t;sp]rep[t;sp]};
 ctf'[t;sep]}

  gcf["testfile";";"]
("200;20.02;300;;0;"
 "40;50;10;;;")
type error
{if[_n~x;:_n];i:1+2*!_.5*#x:(0,/(0,+/~+\(>':0,"["=y)-<':("]"=y$:),0)+/:x _ss y)_ x;,/ :[7=4:z;@[x;i;z];4:z$:;@[x;i;:[;z]];@[x;i;:;z]]}
                                                                         ^
>  
```

**Comment by tavmem** [comment]
Oops ... there is a typo in the k2.8 versions of sim1.k and sim2.k (which is why they fail).
In the final line of both scripts the "sep" should read "sp"
The corrected scripts sim1.k and sim2.k both work in k2.8.

**Comment by tavmem** [comment]
What are seeing in the sim1.k script is that the definition of function "rep" has somehow become hidden from "ctf" when "ctf" is invoked.  In a fresh session of Kona (where "rep" has not been defined) we get:
```
  t:0:"testfile";
  t
("200;20.02;300;;0;"
 "40;50;10;;;")
  
  rep[t[0];";"]
("200;20.02;300;;0;"
 ";")
  rep[t[1];";"]
("40;50;10;;;"
 ";")

  .`
.((`k
   .((`t
      ("200;20.02;300;;0;"
       "40;50;10;;;")
      )
     (`rep;;))
   )
  (`t;-5.9894e+08;))
```
in script sim1.k, the last line ctf'[t;sp] is feeding "rep" the lines of "t" one at a time, but "rep" has essentially become "null" to "ctf".
Kona does not report "value" errors.
In the script sim0.k the defintion of "rep" has not become hidden from "ctf", and the script works.

**Comment by dlorean00004** [comment]
I inserted f:{x@!#x} f (useless in itself) in the getcsvFloat code at Jan 8,  after the first line instead of 
the f:{x@& (#:'x)>0} f . This causes the same error
I then moved the "replacesep /"rep"-equivalent"'s body into the function calling it, and this returns output which is not correct
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
/f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
{1. *' x }'  ChartoFloat\:[f;separator]}
(200 20.02 33 0 5 0.0
 100 0 120 101 87 96.0
 4 53 3.9 43 65 1.0)
ok
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
/f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'  
ChartoFloat\:[f;separator]}
((200;20.02;33;0;5;0)
 100 0 120 101 87 96
 (4;53;3.9;43;65;1))
ok
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'  
ChartoFloat\:[f;separator]}
(5,,,,:,
 (100
  120 101 87 96)
 (4;53;3.9;43;65;1))
not ok

**Comment by tavmem** [comment]
It's not immediately clear why your 3rd scenario fails.
The problem is very likely caused by the same factors causing the original problem.
I need to spend some time debugging the original problem.
In order to do that I need to update my Kona-debugging environment 
https://github.com/tavmem/konaStk
which I have sort of neglected.
I spent yesterday and today updating it, but it still needs some work.
I will be away for the rest of today and most of tomorrow.
Once the original problem is fixed, we can see if your 3rd scenario still fails.
... Cheers.

**Comment by tavmem** [comment]
After commit 6ba97062b3ab97d9d5d7119e0644fd380483d46f
the original problematic script documented in this issue now works
```
  \cat gcf.k
getcsvFloat:{[filename;separator]
f: { x@ & (#:' x) >0 }[ 0:filename ] ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\:[f;separator] ;
}
  
  \l gcf
{[filename;separator]
f: { x@ & (#:' x) >0 }[ 0:filename ] ;
replacesep: {_ssr[x;y;","]} ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing replacesep[dl;sep] } ;
:{1. *' x }' ChartoFloat\:[f;separator] ;
}
  
  getcsvFloat["testfile";";"]
(200 20.02 300 0 0 0.0
 40 50 10 0 0 0.0)
```

**Comment by tavmem** [comment]
The other problematic script documented above (which I am calling scenario 3) still does not yield the correct result:
```
  \cat scn3.k
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'
ChartoFloat\:[f;separator]}
  
  \l scn3
{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'
ChartoFloat\:[f;separator]}
  
  getcsvFloat["testfile";";"]
(200,20.02,300,,:0,;40,50,10,,:,)
```

**Comment by tavmem** [comment]
Though scenario 3 works in k2.8, the formatting of the result is not "optimal"
```
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems

  \cat scn3.k
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'
ChartoFloat\:[f;separator]}
  
  \l scn3
  
  getcsvFloat["testfile";";"]
((200;20.02;300;0;0;0)
 40 50 10 0 0 0)
```

**Comment by tavmem** [comment]
On the other hand, the result format in k2.8 is probably correct:
```
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems

  (200 20.02 300 0 0 0)~200,20.02,300,0,0,0
0
  (200 20.02 300 0 0 0)
200 20.02 300 0 0 0
  200,20.02,300,0,0,0
(200;20.02;300;0;0;0)
```

**Comment by tavmem** [comment]
After commit dd74329ab61815daeb70badcf055fdbdaf24a928 scenario 3 works in Kona
```
  \cat scn3.k
getcsvFloat:{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'
ChartoFloat\:[f;separator]}
  
  \l scn3.k
{[filename;separator]
f:0:filename ;
/:f:{x@& (#:'x)>0} f;
f:{x@!#x} f ;
addmissing:{s:",";:[(*x)=s;_f["0",x];( * |x)=s;x,"0";x]} ;
insertmissing:{s:",";(x,(#x)#"0")@ < (!#x),& (x=s)&1!x=s} ;
replacesep: {_ssr[x;y;","]} ;
ChartoFloat:{[dl;sep]. ": ",insertmissing addmissing {_ssr[x;y;","]}[dl;sep] } ;
/{1. *' x }'
ChartoFloat\:[f;separator]}
  
  getcsvFloat["testfile";";"]
((200;20.02;300;0;0;0)
 40 50 10 0 0 0)
```
