### ISSUE TITLE
4 tests fail in Windows

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#402]
```
Failed. These are not equal:
(,"+") , $(+)
********************************
,"+"
--------------------------------
,"k"

Failed. These are not equal:
"+:" , $(+:)
********************************
"+:"
--------------------------------
"k\000"

Failed. These are not equal:
_ssr" , $(_ssr)
********************************
"_ssr"
--------------------------------
"k\000\000\000"

Failed. These are not equal:
3 4 , d:.((`a;1);(`b;2)); d[]:3 4; d[!d]
********************************
3 4
--------------------------------

```

**Comment by kirbyfan64** [comment]
Is this from #401? I ran the tests, but not on Windows...

**Comment by tavmem** [comment]
Yes, the fist 3 tests were added as part of 401. The 4th test is not.  
But the 4th test only failed once for me.
I have tried the test suite several more times and only the first 3 tests fail. The last one works fine.
The first 3 tests consistently fail.

**Comment by kirbyfan64** [comment]
Sorry...

**Comment by tavmem** [comment]
No problem.
Just one more bug to fix.  :)

**Comment by tavmem** [comment]
In Kona (on Windows), the behavior is different if you don't run the whole test suite.
If you run each of the 3 tests in a fresh Kona/Windows session you get
```
  $(+)
,"+"
  $(+)
"\000\000\000"
```
new session
```
  $(+:)
"+:"
  $(+:)
"\000\000"
```
new session
```
  $(_ssr)
"_ssr"
  $(_ssr)
"_ssr"
  $(_ssr)
"\000\000\000\000"
```

**Comment by tavmem** [comment]
It's not clear exactly why Windows had a problem.
I found that if I avoided using "realloc()" then the problem disappeared.
