### ISSUE TITLE
Subfunctions and apply

### ISSUE THREAD

**Issue by mgoszcz2** [kevinlawler/kona#405]
While writing my own version of Conway's Game of Life in Kona I found that:

      {a:x; {a,x}@2}1 / Hence {a:x; {a,x}.,2}1 too
    (;2)

It _looked_ like it should work. I found a copy of K2.8 (can't find K3 anywhere) and got:

      {a:x; {a,x}@2}1
    1 2

I realise this might look a bit contrived but it made sense in my original implementation:

    R:3 3#{|/x=1 5 6 7 8}'!9
    L:{a:x; +/{y!'x!a}.'(!3 3)-1}

(Interestingly K2.8's monadic `!` can't operate on vectors so this doesn't work with either)
I've pinpointed the issue to `.`  since functions like `{a:x;{x,a}1}2` work as advertised.

**Comment by tavmem** [comment]
I can't look at this til early March.  If someone comes up with a fix, Kevin can merge it.

**Comment by tavmem** [comment]
On Kona:
```
  {a:x; {a,x}@2}1
(;2)
  
  {a:x; {a,x}.,2}1
(;2)
  
  {a:x; {a,x}. 2}1
(;2)
  
  a:1; {a,x}. 2
1 2
  
  a:1; {a,x}@2
1 2
  
  a:1; {a,x}.,2
1 2
```

**Comment by tavmem** [comment]
In Kona:
```
  {a:x; {a,x}2}1
1 2
```
