### ISSUE TITLE
Segmentation Fault while error handling inside .m.h

### ISSUE THREAD

**Issue by mgoszcz2** [kevinlawler/kona#406]
Server `.m.h:{0+x}` SegFaults instead of reporting a type error.

Problem seems to be caused by `X(c)` returning NULL at [kn.c:157](https://github.com/kevinlawler/kona/blob/508b67cf975f51da416c211ece2674ab7c498168/src/kn.c#L157)

```c
K r=X(c); I w=128; C bck[w];
switch(r->t){
```

The crash happens under both OS X and Linux.

**Comment by tavmem** [comment]
As a general reference:
.m.h is described on page 196 of kref.

**Comment by tavmem** [comment]
Another general reference:
The -h listening port option is described on page 80 of kusr.

**Comment by tavmem** [comment]
As a further general reference:
See issue 210.
