### ISSUE TITLE
Kona API does not build on Linux

### ISSUE THREAD

**Issue by PaulBatchelor** [kevinlawler/kona#407]
(Completely new to Kona and K)

In trying to compile libkona.a (make lib), the build fails.

I can get libkona.a to build if I comment out the functions sdf and scd (lines 35 and 36 in src/kapi.c).  Not sure what I break when I do this, but it seems to work. 

Thanks!

-P

**Comment by mgoszcz2** [comment]
`sdf` and `scd` are for registering even loop callbacks (I think.. I was able to find [this](http://web.archive.org/web/20060214100753/http://www.kx.com/technical/documents/cki.pdf).)

I think those lines were supposed be:

```c
I sfn(S s, K(*f)(), I i) { R 0; }
I sdf(I i, I(*f)()) { R kerr("nyi"); } // XXX
I scd(I i) { I r=close(i); if(r)R kerr("file"); R r;} // XXX
```

(Or adding bits of `ts.h` to define FE and NYI)

I thought about submitting a pull request but I wanted to try make `./kepi-test` pass.

**Comment by kirbyfan64** [comment]
What's the build error? It builds correctly for me.

**Comment by PaulBatchelor** [comment]
running "make lib" gives me this:

In file included from src/kapi.c:4:0:
src/kapi.c: In function 'sdf':
src/kona.h:16:11: warning: return makes integer from pointer without a cast [enabled by default]
 #define R return
           ^
src/kapi.c:35:23: note: in expansion of macro 'R'
 I sdf(I i, I(*f)()) { R NYI; } // XXX
                       ^
src/kapi.c: In function 'scd':
src/kapi.c:36:1: warning: parameter names (without types) in function declaration [enabled by default]
 I scd(I i) { I rclose(i); if(r)R FE; R r;} // XXX
 ^
src/kapi.c:36:30: error: 'r' undeclared (first use in this function)
 I scd(I i) { I rclose(i); if(r)R FE; R r;} // XXX
                              ^
src/kapi.c:36:30: note: each undeclared identifier is reported only once for each function it appears in
src/kapi.c:36:34: error: 'FE' undeclared (first use in this function)
 I scd(I i) { I rclose(i); if(r)R FE; R r;} // XXX
                                  ^
src/kapi.c: In function 'jd':
src/kapi.c:40:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 I jd(I d) { I j; K a = gi(d), r = _jd(a); cd(a); j = Ki(r); cd(r); R j; }
                                   ^
src/kapi.c: In function 'dj':
src/kapi.c:41:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 I dj(I j) { I d; K a = gi(j), r = _jd(a); cd(a); d = Ki(r); cd(r); R d; }
                                   ^
make: *** [src/kapi.o] Error 1

**Comment by mgoszcz2** [comment]
Fails on OS X with clang too.

**Comment by fenollp** [comment]
seems `FE` which is defined in ts.h isn't included in kapi.c nor kona.h

**Comment by tavmem** [comment]
Just as a note:
This issue is a regression.
"make lib" compiles in commit c311ae9524bbccf732a4601f88ed1ee6eda22d60 of Aug 5, 2015.
"make lib" fails in commit b1ed4b9ee34a83c79901225b2172b90fface3356 also of Aug 5, 2015.
