### ISSUE TITLE
Assignment within a function breaks following dyadic functions called on a lambda

### ISSUE THREAD

**Issue by mgoszcz2** [kevinlawler/kona#408]
While working on a trivial parser I found that following an assignment with a dyadic function call with a lambda as an argument.. a mouthful

* It appears to only happen when `c` is dyadic despite `y` being ignored.
* Printing `x` shows the lambda is correctly passed into the function each time
* Adding _any_ **assignment** before the call somehow makes call to `x` within `c` not work (returns nil)
* Bug is _very_ sensitive to the content of the `c` function (Simply adding brackets around `$x` makes it work again)

Here's the code:

```
c:{y; `0:$x; x 2}
`0:"\nWith assignment:"
{a:(); c[{x};()]}[]
`0:"\nWithout assignment:"
{c[{x};()]}[]
\\
```

With Kona:
```
mgoszcz2@jurassic ~ $ ./k bug
K Console - Enter \ for help

  
With assignment:{x}
Without assignment:{x}2
mgoszcz2@jurassic ~ $
```

With K2.8:
```
mgoszcz2@jurassic ~ $ ./klinux bug 
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
Evaluation. Not for commercial use. 
\ for help. \\ to exit.


With assignment:{x}2

Without assignment:{x}2

mgoszcz2@jurassic ~ $
```

The spacing difference is caused by Kona not printing a new line after nil (which is the correct behaviour)
This might appear contrived but it broke my filter function `{y@&x'y}` used after an assignment.

**Comment by tavmem** [comment]
This issue appears to be resolved (probably by fixing other issues).
```
~/kona $ cat bug.k
c:{y; `0:$x; x 2}
`0:"\nWith assignment:"
{a:(); c[{x};()]}[]
`0:"\nWithout assignment:"
{c[{x};()]}[]

~/kona $ rlwrap ./k bug.k
K Console - Enter \ for help
  
With assignment:{x}2

Without assignment:{x}2
```

**Comment by tavmem** [comment]
This issue was fixed by the work of @mgoszcz2 in resolving issue 409.
