### ISSUE TITLE
Following a replace amend with a semicolon causes a valence error

### ISSUE THREAD

**Issue by mgoszcz2** [kevinlawler/kona#411]
This works as expected:

```
  @[!2;0;+;1]
1 1
```

but adding a semicolon:

```
  @[!2;0;:;1];
valence error
@[!2;0;:;1];
       ^
```

**Comment by tavmem** [comment]
This is a regression.
It works in commit 1559a7a2684a0a46cfb880d9fceb10f226ed48e2 of Dec 29, 2014.
I fails in commit ec76647db6387a01edaeaea04c98101b140e7acd of Dec 30, 2014.
