### ISSUE TITLE
Segfault when showing \\

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#413]
All of the following segfault:

```
(\\)
if[1;\\]
do[5;\\]
;\\
```

In K2, they all do...nothing.

**Comment by kirbyfan64** [comment]
Actually, this is because executing the `\\` returns `8`. Which `show` then tries to...show.

**Comment by tavmem** [comment]
Here is some interesting stuff with k2.8 & k3.2
```
  (\) 3 3
3 3
3 3

  (\\) 3 3
3 3
,3 3

  (\) (\) 3 3
3 3
3 3
3 3

  (\) (\\) 3 3
3 3
,3 3
,3 3

  (\\) (\) 3 3
3 3
3 3
,3 3

  (\\) (\\) 3 3
3 3
,3 3
,,3 3
```

**Comment by tavmem** [comment]
Undocumented functionality ?

**Comment by tavmem** [comment]
It's  "Scan-Scan" or "DobleScan":
in k2.8 and k3.2
```
  f:(\\)
  g:(\)\
  f
\\
  f~g
1
```

**Comment by tavmem** [comment]
In k2.8 and k3.2
```
  (\\)2 3
2 3
,2 3

  (\)\2 3
2 3
,2 3
```
This is "Scan Monad"
f\ x
as documented on page 139 of kref.

**Comment by tavmem** [comment]
In Kona:
```
  (\) 2 3
2 3
2 3
  (\)\ 2 3
2 3
,2 3
  
  
  f:(\)\
  g:(\\)
Segmentation fault
```
