### ISSUE TITLE
Group (=) and integer vectors with leading zero

### ISSUE THREAD

**Issue by sgreben** [kevinlawler/kona#416]
Group (=) seems to treat a leading 0 in an integer vector as distinct from all other values:

      = 0 0   
    (,0
     ,1)
    
      = 0 1 0 
    (,0
     ,1
     ,2)
    
     = 0 0 1 0
    (,0
     1 3
     ,2)

      = 0 1 0 2
    (,0
     ,1
     ,2
     ,3)
    
      = 0 1 0 0
    (,0
     ,1
     2 3)     

This does not occur for heterogeneous lists:    

    = (0;1;0;`a)
    (0 2
     ,1
     ,3)

**Comment by tavmem** [comment]
This is a regression:
It works fine in commit d52f0b346156122568ac5c052524af7c77adfeb6 of Nov 29, 2015.
It's broken in commit e8673c0df9ec4fc9f3e705f6d77b89f529d02d4d also of Nov 29, 2015.
