### ISSUE TITLE
Invalid behaviour of each on length 1 sequences 

### ISSUE THREAD

**Issue by mgoszcz2** [kevinlawler/kona#417]
Both `#:',0` and  `#:',,0` return `1` instead of `,1`.

This is a serious problem at it introduces bugs in seemingly innocent code when length of sequence is 1. Simple code like `{x@>#:'x}[,1]` breaks.

Both oK and K2.8 correctly return `,1` for both snippets

**Comment by tavmem** [comment]
This is a regression.
Both work fine in commit 9c7562f5d58e8947bdc524eb34c21db2328a8d7f of Sep 27, 2014.
Both fail in commit f689f4f7332e2a5531776dcc668a408207d4969f of Sep 28, 2014.
