### ISSUE TITLE
"value error" for any variable I define.

### ISSUE THREAD

**Issue by genos** [kevinlawler/kona#423]
Any variable I define causes `kona` to print `value error`, prior to printing the variable's value.

      a:1
      a
    value error
    1

Downloaded latest version as of 2016/03/31, i.e. commit d67d39c

**Comment by tavmem** [comment]
So far, the code examines the initial parse string and then the substrings parsed in the "recursive descent" process.  It checks whether "amend" is present, and for other conditions that indicate whether a "value error" should be reported.  That is clearly not adequate.

Once a name is identifed as a potential "value error", the code needs to check whether a corresponding entry already exists on the KTREE.  If yes, then no "value error" condition exists.

An identifed name is in the form of a string.  The entries in the KTREE are interned strings.  It seems more efficient to compare the identifed name as an interned string to the KTREE entries.

A potential shortcut is the "interned string pool".  If a corresponding entry does not already exist in the "interned string pool", then it cannot already exist on the KTREE.  (If it does exist in the "interned string pool", then it may, or may not, already exist on the KTREE, and the code needs to check the KTREE.)

To prevent cluttering the "interned string pool" with bogus names, it would be best to check whether the candidate already exists in the "interned string pool".  If no, report a "value errror", but do not add the entry to the "interned string pool".  If yes, then proceed to check whether that interned string exists in the KTREE.

**Comment by tavmem** [comment]
As the next step toward a full implementation, do the check against the "interned string pool".  At a minimum, this would fix the case identified in this issue.

If a candidate is already in the "interned string pool" do not report a "value error".  While this would fail to report "value error" for candidates in the "interned string pool" that are not on the KTREE, it would eliminate the bogus reporting identified in this issue.

**Comment by tavmem** [comment]
The shortcut does not work.
By the time the parser is deciding whether to add the new symbol to the KTREE (or not) ...
the symbol is already in the "interned string pool".

The code needs to check if the symbol is already in the KTREE.

**Comment by tangentstorm** [comment]
@genos as a workaround until @tavmem does his magic, I just turned off the message by commenting out line 601 in `p.c`.

(Thanks for the amazing transparency and helpful comments on all your tickets, @tavmem! I wish everyone posted their notes like this.)

**Comment by tavmem** [comment]
@tangentstorm :  Thanks for the complement!

As an alternate workaround for anyone bothered by the spurious "value error" messages: 
You can checkout the code as of a prior release before compiling.

**Comment by genos** [comment]
Wow! I was not expecting such a well thought out fix nearly this quickly. Thanks very much!

**Comment by tavmem** [comment]
You're welcome !
