### ISSUE TITLE
`_ssr` verb no longer produces output

### ISSUE THREAD

**Issue by tangentstorm** [kevinlawler/kona#433]
The test for this verb is passing but the actual result is not displayed:

      "ebcd" = _ssr["abcd";"a";"e"]
    1 1 1 1
      / however:
      _ssr["abcd";"a";"e"]
      / (no output)

Issue #302 seems to indicate that this produced the expected output at one point.

Note that other string expressions work just fine:

      "",_ssr["abcd";"a";"e"]
    "ebcd"

**Comment by tavmem** [comment]
This is a regression.
It last worked in the commit 566c9e1f48584821741b27d9ad8ff06b8239ebf3
made on Jan 20, 2016 titled "better for ARM processors and 32-bit Android"

It was broken by commit 43b5962366f215038d012cdaf665c44fcafec01c
also made on Jan 20, 2016 titled "fix 353: trial implementation of print suppression"

Looks like the "print suppression" went a bit too far.

**Comment by tavmem** [comment]
A quick fix will reopen issue #353 (which is fine).
Can re-address 353 later.
