### ISSUE TITLE
k vs. k_test

### ISSUE THREAD

**Issue by raould** [kevinlawler/kona#435]
I am apparently confused about how these differ. I guessed at first k_test was a test suite. But then somewhere I forget where implied k_test was like a verbose debug mode of k. But they seem to have different behaviour for something like the stuff below. "k" seems to be whitespace insensitive, "k_test" appears to be sensitive. (Linux Ubuntu 14.04 LTS 32bit x86, cloned repo as of aac5b17bc2763104169a389dc5806a4b26e3a86b)

```
d[`a]:4
```
vs.
```
d[`a]: 4 /notice the space before the 4
```

**Comment by bakul** [comment]
On Sat, 16 Apr 2016 23:36:21 PDT Raoul Duke <notifications@github.com> wrote:
> 
> I am apparently confused about how these differ. I guessed at first k_test wa
> s a test suite. But then somewhere I forget where implied k_test was like a v
> erbose debug mode of k. But they seem to have different behaviour for somethi
> ng like this:
> 
> ```
> d[`a]:4
> ```
> vs.
> ```
> d[`a]: 4 /notice the space before the 4
> ```

This seems to be some initialization bug in k_test.  After the
tests complete, hit return once and they will behave the same
way.

**Comment by raould** [comment]
thanks!

**Comment by tavmem** [comment]
k_test is a test suite.
There does seem to be some initialization bug in k_test.
