### ISSUE TITLE
dictionary docs

### ISSUE THREAD

**Issue by raould** [kevinlawler/kona#436]
hi, I am confused about dictionaries. I want to avoid populating / polluting the k global dictionary more than I have to. I want to make nested dictionaries. How would I go about making something like this example in javascript?
https://repl.it/CG4K/0
```
var d = { 'wr' : { 'w' : 1024, 'h' : 100 } };
console.log( [ d, d['wr'], d['wr']['h'] ] );
```

**Comment by bakul** [comment]
On Sat, 16 Apr 2016 23:47:36 PDT Raoul Duke <notifications@github.com> wrote:
> 
> hi, I am confused about dictionaries. I want to avoid populating / polluting 
> the k global dictionary more than I have to. I want to make nested dictionari
> es. How would I go about making something like this example in javascript?
> https://repl.it/CG4K/0
> ```
> var d = { 'wr' : { 'w' : 1024, 'h' : 100 } };
> console.log( [ d, d['wr'], d['wr']['h'] ] );

      d:.+(,`a;,(.+(`b`c;1 2)))
      d.a.c
    2

The kona-users mailing list may be a better place for such questions.

**Comment by raould** [comment]
Interesting, that's another syntax I didn't notice/see in the 'dictionary' wiki page. :-) Thanks. Yes, I will get on the list.
