### ISSUE TITLE
Regression with curried ?

### ISSUE THREAD

**Issue by kirbyfan64** [kevinlawler/kona#443]
This used to work in a previous version of Kona.

In K2:

```
ryan@DevPC-LX:~$ rlwrap k2
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
Evaluation. Not for commercial use. 
\ for help. \\ to exit.

  ("+-<>[]."?)'"+-+-"
0 1 0 1
  ?["+-<>[].";]'"+-+-"
0 1 0 1
  
ryan@DevPC-LX:~$ 
```

In Kona:

```
ryan@DevPC-LX:~$ rlwrap k
K Console - Enter \ for help

  ("+-<>[]."?)'"+-+-"
("+-<>[]."?["+";];"+-<>[]."?["-";];"+-<>[]."?["+";];"+-<>[]."?["-";])
  ?["+-<>[].";]'"+-+-"
(?["+-<>[].";"+";];?["+-<>[].";"-";];?["+-<>[].";"+";];?["+-<>[].";"-";])
  
ryan@DevPC-LX:~$ 
```

**Comment by tavmem** [comment]
I was unable to find any previous version of Kona where this worked.

If you can find a previous version in which it worked, that would be great ... then we can see what code changes caused the regression.

In any case (whether or not it is a regression), we can treat it as a "bug", and it does need to be fixed.

**Comment by kirbyfan64** [comment]
@tavmem I don't believe the first ever worked. The second broke was broken by https://github.com/kevinlawler/kona/commit/b9c6ed7bedfddecaa0d1a5fa76da714eb36bc880. (Man, I love `git bisect`. :)

**Comment by tavmem** [comment]
Thanks!  (I only checked the first one.)

**Comment by tavmem** [comment]
Commit 4eb006a9f1d8aba12aeb5009de3ba335bc62a606 resolves the regression portion.
Case 2 works again.
