### ISSUE TITLE
-10.0 < 20 returns 0 instead of 1

### ISSUE THREAD

**Issue by danbek** [kevinlawler/kona#457]
Current master of kona gives the following incorrect result:

    $ ./k
    K Console - Enter \ for help
    
      -10.0 < 20
    0

The bug seems to have been introduced in the commit https://github.com/kevinlawler/kona/commit/0e69e2e.

**Comment by tavmem** [comment]
bug fixed with code from pahihu
see "FC() fix" at https://github.com/pahihu/kona
