### ISSUE TITLE
Monte Carlo method

### ISSUE THREAD

**Issue by Kokokokoka** [kevinlawler/kona#459]
While studying the examples which are presented in rosetta stone.
I've found that those results differ.
http://rosettacode.org/wiki/Monte_Carlo_methods#K
on rosetta:
```
 sim:{4*(+/{~1<+/(2_draw 0)^2}'!x)%x}
 
   sim 10000
3.103
 
   sim'10^!8
4 2.8 3.4 3.072 3.1212 3.14104 3.14366 3.1413
```
kona:
```
  sim:{4*(+/{~1<+/(2_draw 0)^2}'!x)%x}
{4*(+/{~1<+/(2_draw 0)^2}'!x)%x}
     sim 10000
0
   sim'10^!8
0 2.8 3.08 3.144 3.1568 3.13864 3.137924 3.141274
```
am I missing something?

**Comment by bakul** [comment]
On Wed, 17 May 2017 03:49:16 PDT Kokokokoka <notifications@github.com> wrote:
> 
> While studying the examples which are presented in rosetta stone.
> I've found that those results differ.
> http://rosettacode.org/wiki/Monte_Carlo_methods#K
> on rosetta:
>
>  sim:{4*(+/{~1<+/(2_draw 0)^2}'!x)%x}
>  ...
>  sim'10^!8

There are two errors in your code + a difference in k vs kona
semantics. In kona % is an integer divide. I will leave
actual debugging this to you since there is no kona bug :-)
