### ISSUE TITLE
indexing a dictionary by list of keys is broken.

### ISSUE THREAD

**Issue by tangentstorm** [kevinlawler/kona#460]
t:.+(`f`g`h;3 10 _draw 10);  / a dictionary with 3 keys.
      t@`f`g`h                     / this works
    (7 9 7 1 9 0 6 5 1 9
     2 0 4 1 8 8 9 5 5 8
     7 3 1 2 9 7 7 8 1 1)
      t`f`g`h                      / should be the same, but there's no output.
      4: t`f`g`h                   / no output here either. (as if it doesn't even have a type?!)

**Comment by tavmem** [comment]
Interestingly, it works when using only 1 key:
  t:.+(`f`g`h;3 10 _draw 10)
  t@`f
2 7 8 0 8 0 0 1 1 5
  t`f
2 7 8 0 8 0 0 1 1 5

**Comment by tavmem** [comment]
And yields a type error when using 2 keys:

  t@`f`g
(2 7 8 0 8 0 0 1 1 5
 8 9 7 4 1 9 8 3 2 0)

  t`f`g
type error
>
