### ISSUE TITLE
[Question] Meaning of '4:'

### ISSUE THREAD

**Issue by ac1235** [kevinlawler/kona#473]
As far as I know, ":" is the amend verb.
However, the syntax "number:" obviously doesn't amend the numeric constant.
This does not seem to be documented in the wiki.
What's the meaning of those expressions?

**Comment by bakul** [comment]
Use kona-user@googlegroups.com mailing list for questions/discussion. Report Bugs via the github issue page for kona.

Type \: in Kona to get a brief description of various “number:” monadic and dyadic forms.

4: expr returns the expr type.
h 4: string sends string, which should contain a valid expression, to a remote instance of kona and returns its result.

**Comment by tavmem** [comment]
Please see the K 2.0 Reference Manual and the K 2.0 User Manual reachable via "Links" in the Kona wiki.
