### ISSUE TITLE
Some warnings when building with -Wall on clang-5.0.0

### ISSUE THREAD

**Issue by ibara** [kevinlawler/kona#485]
Hi --

When I turn -Wall on, below are the only warnings that pop up.
This is on OpenBSD, clang-5.0.0 as the compiler.
Clang has -Wempty-body on by default, so that one always pops up. The other may be a false positive, hence why I'm submitting this as an issue and not as a pull request.

Thanks!

```
cc -O2 -pipe -pthread -Wall    -c -o src/0.o src/0.c  
src/0.c:157:8: warning: variable 'f' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
    if(m[0])f=open(m,O_RDWR|O_CREAT|O_TRUNC,07777); 
       ^~~~                                           
src/0.c:158:7: note: uninitialized use occurs here    
    P(f<0,DOE)                                        
      ^                                               
src/ts.h:91:20: note: expanded from macro 'P'         
#define P(x,y) {if(x)R(y);}                           
                   ^                                      
src/0.c:157:5: note: remove the 'if' if its condition is always true                                                                                 if(m[0])f=open(m,O_RDWR|O_CREAT|O_TRUNC,07777);                                                                                             
    ^~~~~~~~                  
src/0.c:135:22: note: initialize the variable 'f' to silence this warning                                                                       
  S m=CSK(a); I s=0,f;           
                     ^                                                                                                                          
                      = 0       
src/0.c:560:38: warning: if statement has empty body [-Wempty-body]                                                                             
    CSR('\007',) CS('\010', if(1==xn);    ) //TODO - seven_types on disk  (1==xn --> no size increase)
                                     ^
src/0.c:560:38: note: put the semicolon on a separate line to silence this warning
2 warnings generated.
```

**Comment by tavmem** [comment]
In an attempt to replicate this issue, I installed OpenBSD-6.2 as a guest VM on Fedora-27 with KVM/QEMU.   I am trying to access the text console of the OpenBSD domain from "virsh" on Fedora.

The guest VM needs its serial console to be populated with a login prompt, which will present itself upon a successful serial connection from virsh.

The process is documented for an Ubuntu guest at 
http://www.jaredlog.com/?p=1484
However, OpenBSD-6.2 does not have an  /etc/init   directory.
Do you know how would I set up a similar automatic login prompt in OpenBSD?

**Comment by bakul** [comment]
I haven't used qemu in ages and certainly never on kvm host
but if you can start qemu from the command line, try this:

    qemu ..... -serial stdio

This will connect your tty to the qemu console. Or you can
connect it to a network port:

    qemu .... -serial telnet:127.0.0.1:1234,server,nowait

and then 

    telnet 127.0.0.1 1234

**Comment by tavmem** [comment]
Thanks for the response ...

I had been able to get to a QEMU/KVM console using
$ virt-manager -c openbsd6
But the console was only 25 x 80 with no scroll capability.

I was hoping that the folllowing would give a better console.  (Doesn't work with OpenBSD guest.) 
$ virsh -c qemu:///system
virsh # console openbsd6
Connected to domain openbsd6
Escape character is ^]

Both of the following also get me directly to  25 x 80 QEMU conole with no scrolling:
$ qemu-system-x86_64 -serial stdio /var/lib/libvirt/images/openbsd6.img
$ qemu-system-x86_64 -serial telnet:127.0.0.1:1234,server,nowait /var/lib/libvirt/images/openbsd6.img

The last option does not seem to allow the opportunity to enter your last command one in the QEMU console:
elnet 127.0.0.1 1234

Plan:
I will try to get "ssh" to work.
If not, I will probably try to install OpenBSD-6.2 under Oracle VM

**Comment by ibara** [comment]
You can use tmux to get scrollback. Tmux is part of the OpenBSD base install.

**Comment by tavmem** [comment]
Thanks ... tried tmux in both a QEMU/KVM console, and a QEMU console.
It turns out that command scrollback is already available in both the QEMU/KVM and the QEMU consoles, going back to all commands executed in the current console session.

tmux did not help in expanding the number of lines didplayed in the console, or srolling back on console output using either the QEMU/KVM or QEMU consoles.

Will try a few other things later this week.

**Comment by bakul** [comment]
Add -nographic to the command line.

qemu-system-x86_64  -nographic -serial stdio /var/lib/libvirt/images/openbsd6.img

**Comment by tavmem** [comment]
I was away from computers for the whole weekend.
FYI,  Adding "-nographic" causes other problems:

$ qemu-system-x86_64 -nographic -serial stdio /var/lib/libvirt/images/openbsd6.img
QEMU 2.10.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: -serial stdio: cannot use stdio by multiple character devices
qemu-system-x86_64: -serial stdio: could not connect serial device to character backend 'stdio'
$

**Comment by bakul** [comment]
Looks you need to remove -serial stdio as -nographic redirects to serial console to stdio.

If you need network connectivity to download kona, see [https://wiki.qemu.org/Hosts/BSD#OpenBSD](url)

**Comment by tavmem** [comment]
Yeah ... I tried removing   -serial stdio
It seems to put me in the same exact spot that I end up in using virsh:
```
$ sudo virsh start openbsd6
Domain openbsd6 started
$ virsh -c qemu:///system
Welcome to virsh, the virtualization interactive terminal.
Type:  'help' for help with commands
       'quit' to quit
virsh #  console openbsd6
Connected to domain openbsd6
Escape character is ^]
```
That is to say that I seem to get connected to openbsd6, but there is no login prompt.

Plan:  Switch to Oracle VM VirtualBox.

**Comment by bakul** [comment]
I installed it in qemu and see what is happening.
My guess the screen is used as its console and no login is enabled on the serial line. You need to switch console to serial. If you still have a working installation, edit /etc/ttys and change the tty0 line as follows

  tty00   "/usr/libexec/getty std.9600"   vt220    on secure

save it, shutdown openbsd VM gracefully with "shutdown now" and then restart *qemu* with the `-serial stdio` option. `-nographic` is not needed.

**Comment by tavmem** [comment]
Thanks !!!
It worked, but in an unexpected manner:
I modified /etc/ttys and gracefully shutown openbsd and then restarted it with the command:
```
$ qemu-system-x86_64 -serial stdio /var/lib/libvirt/images/openbsd6.img
```
As usual, a new 25 x 80 graphic console came up using ttyC0, and displayed the startup process.
However, after startup completion, a "login: " prompt appeared on the original console.
If I kill the graphic console, the openbsd6 session in the original console also terminates.
The complete set of messages on the original console was:
```
$ qemu-system-x86_64 -serial stdio /var/lib/libvirt/images/openbsd6.img

(qemu-system-x86_64:3195): Gtk-WARNING **: Allocating size to GtkScrollbar 0x560a2f9c2380 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(qemu-system-x86_64:3195): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1123786328 and height 400

(qemu-system-x86_64:3195): Gtk-WARNING **: Allocating size to GtkScrollbar 0x560a2f9c2580 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(qemu-system-x86_64:3195): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1123786328 and height 400

OpenBSD/amd64 (I-13.my.domain) (tty00)

login: tom
Password:
Last login: Mon Feb  5 23:57:56 on tty00
OpenBSD 6.2 (GENERIC) #132: Tue Oct  3 21:18:21 MDT 2017

Welcome to OpenBSD: The proactively secure Unix-like operating system.
```

**Comment by ibara** [comment]
Sorry for taking so long to respond to this.
@tavmem -- would you like an account on one of my machines? I can set you up no problem.

**Comment by tavmem** [comment]
@ibara :  No problem on the timing of your response.
Thanks for the offer for an account on your machine.
As you know, this is not a high priority bug, so I'd rather keep puttering around trying to set up an OpenBSD VM on a Fedora host machine.

**Comment by tavmem** [comment]
This entry just documents the current problem, and the planned next step.
```
# cat /etc/installurl
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/6.2/packages/amd64/
```
```
# pkg_add git                                                           
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/6.2/packages/amd64//6.2/packages/amd64/: no such dir
Can't find git
```
Note the discrepancy between /etc/installurl and where pkg_add actually looked.
I believe this is because I made a typo in the original set up of /etc/installurl
After correcting the typo, pkg_add began to use a composite of the new correct and old bogus names.

Next step:  re-install OpenBSD.
However, instead of using "virt-install" again, I may try the qemu installer.

**Comment by ibara** [comment]
Oh, this line:
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/6.2/packages/amd64/
should be:
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/

**Comment by tavmem** [comment]
Made the fix ... still having a problem.
```
# cat /etc/installurl
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/
# pkg_add git         
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64//6.2/packages/amd64/: no such dir
Can't find git
```
Tried an alternate ... looks like it found the directory ... no git
```
# cat /etc/installurl
https:/ftp.openbsd.org/pub/OpenBSD
# pkg_add git               
Can't find git
```
Next step:  will try some other alternatives tonight.

**Comment by tavmem** [comment]
Got git.  There was another typo (the double slash):
```
# cat /etc/installurl
https://ftp.openbsd.org/pub/OpenBSD
# pkg_add git                
quirks-2.367 signed on 2017-10-03T11:21:28Z
quirks-2.367: ok
git-2.14.2:nghttp2-1.26.0: ok
git-2.14.2:curl-7.55.1: ok
git-2.14.2:libiconv-1.14p3: ok
git-2.14.2:gettext-0.19.8.1p1: ok
git-2.14.2:cvsps-2.1p0: ok
git-2.14.2:p5-Error-0.17024: ok
git-2.14.2:rsync-3.1.2p0: ok
git-2.14.2: ok
The following new rcscripts were installed: /etc/rc.d/gitdaemon /etc/rc.d/rsyncd
See rcctl(8) for details.
Look in /usr/local/share/doc/pkg-readmes for extra documentation.
#
```

**Comment by tavmem** [comment]
Status:  I only got 1 warning on src/0.c when using gmake.
```
src/0.c:560:38: warning: if statement has empty body [-Wempty-body]
    CSR('\007',) CS('\010', if(1==xn);    ) //TODO - seven_types on disk  (1==xn --> no size increase)
                                     ^
src/0.c:560:38: note: put the semicolon on a separate line to silence this warning
1 warning generated.
```
However, the default installed version is clang-4.0.0
```
$ clang --version
OpenBSD clang version 4.0.0 (tags/RELEASE_400/final) (based on LLVM 4.0.0)
Target: amd64-unknown-openbsd6.2
Thread model: posix
InstalledDir: /usr/bin
```
Planned next step:  Try to upgrade to clang-5.0.0.
I may also need to upgrade LLVM also.

**Comment by tavmem** [comment]
Ah ... I did not turn -Wall on.  That may be the difference.

**Comment by ibara** [comment]
If you need to upgrade clang, run `# pkg_add llvm` and see what the output of `$ /usr/local/bin/clang --version` says.
If that's also 4.0.0, you probably need to reinstall OpenBSD from a -current snapshot (which can be grabbed from here: cdn.openbsd.org/pub/OpenBSD/snapshots/amd64/). The process is the same, except during the install and in /etc/installurl, you replace 6.2 with snapshots.

**Comment by tavmem** [comment]
Just as a point of interest:  When I use gcc and turn -Wall on, I get no similar message.
(This comment does not imply that the uninitialized condition is OK.)

**Comment by ibara** [comment]
clang is much more strict than gcc. I think only the newest gcc releases are as strict as clang has always been.

**Comment by ibara** [comment]
Thanks!
