### ISSUE TITLE
"flatten" scalar results in garbage data, (sometimes) crash

### ISSUE THREAD

**Issue by hoosierEE** [kevinlawler/kona#514]
```K Console - Enter \ for help

  a:1
1
  ,//a
1
  a
()
  a
�r" (nil)  
  ,//a
()
  a
�r" (nil)  
  a
()
  ,//a
rlwrap: warning: k crashed, killed by SIGSEGV (core dumped).
rlwrap itself has not crashed, but for transparency,
it will now kill itself with the same signal


warnings can be silenced by the --no-warnings (-n) option
Segmentation fault (core dumped)
```

Seems like the crash doesn't always happen right away, and the "garbage text" is different each time I restart Kona.

**Comment by tavmem** [comment]
Thanks!  This bug is a regression.  
It worked through commit 84eda9efef57f0cf9b49be747bf5251cfb47d9a8 made on Oct 20, 2015.
It was broken by commit c71477ccee04f684fd4d4820d5cac843fdc5ab59 also made on Oct 20, 2015.

**Comment by hoosierEE** [comment]
Awesome, thanks!
