### ISSUE TITLE
Partial console output 

### ISSUE THREAD

**Issue by bakul** [kevinlawler/kona#522]
When the user explicitly asks to print out a value, kona should print the whole list and not a partial one with ellipsis at the end.
````
  !1000

\ ends with ... after showing the first 501 numbers
````

**Comment by ngn** [comment]
out of curiosity, what would "not explicitly" be? or do you mean it should always print the complete value?

**Comment by bakul** [comment]
Yes it should always print the complete value, just like k3. If the user doesn't want any output he can append a `;` at the end.

**Comment by ngn** [comment]
that's easy - delete lines [208](https://github.com/kevinlawler/kona/blob/da36d6b643878a8db1afa9a9d324ded86fd3dff8/src/k.c#L208) [224](https://github.com/kevinlawler/kona/blob/da36d6b643878a8db1afa9a9d324ded86fd3dff8/src/k.c#L224) [225](https://github.com/kevinlawler/kona/blob/da36d6b643878a8db1afa9a9d324ded86fd3dff8/src/k.c#L225) and all occurrences of `CPMAX` in `k.c`
