### ISSUE TITLE
flip of a scalar

### ISSUE THREAD

**Issue by ngn** [kevinlawler/kona#527]
This is not a bug. I think Kona is consistent in its impl of `+x` - it reverses the leading min(2,rank(x)) dimensions, but you might be interested anyway in having a peek at: https://github.com/JohnEarnest/ok/issues/77 in which I argue for `(+1) ~ ,,1` and `(+1 1) ~ ,1 1`.

**Comment by tavmem** [comment]
Thanks ... I appreciate the suggestion ... and the reference to ok#77.
At this point kona is attempting to mimic the behavior of k2.8 and k3.2 as much as possible.

```
K 2.8 2000-10-10 Copyright (C) 1993-2000 Kx Systems
Evaluation. Not for commercial use. 
\ for help. \\ to exit.

  + 1 1
1 1
  +1
1
```
k3.2 gives the same results.
