### ISSUE TITLE
Domain error when invoking help menus

### ISSUE THREAD

**Issue by hoosierEE** [kevinlawler/kona#528]
Each of these produce a domain error:

- `\0` - domain error
- `\+` - domain error
- `\'` - domain error
- `\:` - domain error
- `\_` - domain error

The other items in the help menu do not produce a domain error:

- `\b`
- `\d`
- `\e`
- etc.

Seems to be a problem only with the non-alphabetical menus.

**Comment by hoosierEE** [comment]
Is there a way to set `\e 0` from the command-line when starting the kona console?  That would be fine as a workaround for me.

**Comment by bakul** [comment]
This error seems to be introduced in the c047ce9b636 commit.

    git diff 862092169 c047ce9b6

reveals this is a small change. This fix was made to produce a `domain error` for `\3` but broke other things. Tom will have to come up with a proper fix `\3` to produce a `domain error` but until then perhaps you can revert this one change in your own copy?

**Comment by hoosierEE** [comment]
Works for me, thanks!
