### ISSUE TITLE
Enumerate noun does not display anything

### ISSUE THREAD

**Issue by kritixilithos** [kevinlawler/kona#532]
`!noun` does not print anything to the repl, similarly a list like `2 3 5` does not either.

Shown below is a sample repl session.

```
  4+2
6
  !4
  !2 4
(0 0
 0 1
 0 2
 0 3
 1 0
 1 1
 1 2
 1 3)
  3+2 4
  2+4
6
```

**Comment by tavmem** [comment]
This problem was caused by the latest commit.
I will reverse that commit, and investigate further.
