### ISSUE TITLE
how to add new data type, such as datetime?

### ISSUE THREAD

**Issue by fouvy** [kevinlawler/kona#546]
I wanna add some new date type, any doc about add new data type?

**Comment by tavmem** [comment]
If you want to add some new data type within Kona, you can setup a function to do that.
For example, if you want to add datetime:
```
  _ltime _t
20190705 205947

datetime:{_ltime _t}
  datetime()
20190705 210106
```
If you want to add some new data type to the underlying C code:
All the datatypes are defined in src/ts.h
```
