### ISSUE TITLE
: for resume doesn't work

### ISSUE THREAD

**Issue by bakul** [kevinlawler/kona#563]
Consider:
```
  4 # 3 + "x"
type error
4 # 3 + "x"
      ^
>
```
At this stage one should be able to resume the parent expression as follows.
```
> : 3 + 7
10 10 10 10
  "back at the top level"
```
 Kona behaves as follows.
```
> : 3 + 7
10
> "still one level down"
```

**Comment by tavmem** [comment]
Based on a review of the **Dispatch Table** in src/k.c:
There has never (yet) been an attempt to implement **resume**.
