### ISSUE TITLE
Value error only on first expression

### ISSUE THREAD

**Issue by ibara** [kevinlawler/kona#580]
Hi --

I have an odd bug on the latest checkout I'm not sure how to diagnose (besides triaging which commit introduced the bug, which I'm happy to do).

See the included log, but in short, when you run k, the first prompt doesn't have the > prompt character and generates a value error. Subsequent expressions are fine.

Thanks!
[k.txt](https://github.com/kevinlawler/kona/files/4017953/k.txt)

**Comment by tavmem** [comment]
Hi -
I did a fresh clone of kona using Fedora linux.
I was unable to replicate the bug you experienced.
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  1+2
3
  1+2
3
```
What environment are you using?

**Comment by ibara** [comment]
Ah. I should have mentioned that. But you should always assume I'm on OpenBSD :)
OpenBSD/amd64 in this case. Compiler is clang-8.0.1 but the same problem occurs with gcc-8.3.0.

I can triage tomorrow.

**Comment by ibara** [comment]
Hmm... I just retried on some other OpenBSD/amd64 machines and everything is OK on all the others. So appears it's a local problem on that specific machine.

Sorry for the noise!

**Comment by tavmem** [comment]
If the problem persists on that machine ...
there may be a kona bug that appears only in a very specific environment.
