### ISSUE TITLE
Update in-app documentation to reflect functionality moved to _draw

### ISSUE THREAD

**Issue by gitonthescene** [kevinlawler/kona#609]
Per the discussion in #320 and related issues, updating the in-app documentation to reflect that `?` no longer supports the functionality moved to `_draw`.

Note that the documentation for `_draw` has been updated as well.  The line is 104 characters long, but still not the longest.  I'm open to suggestions if this is not acceptable.

**Comment by tavmem** [comment]
I expected that you would have been added to the contributor list to kevinlawler/kona.
It obviously did not happen.
In the future ...
-- rather than making the improvement in your clone  and then, having me merge the fix
-- commit the change directly to kevinlawler/kona and let me (or Kevin) approve the commit.

**Comment by gitonthescene** [comment]
Sure.  I haven’t followed this model before and I’m slightly confused.  Do you want me to post a diff somehow that gets reviewed?  Or should I commit to the master branch and you’ll revert it if necessary?  Should I commit to the master branch?

**Comment by tavmem** [comment]
No ...
I am not requesting you to do anything.

I thought that when you applied the documentation fix to your clone and then I merged it, you would get credit in kevinlawler/kona as as contributor.  That did not happen.  So, in the future, if you fix some other problem in kevinlawler/kona we should use a different approach.

I'm guessing that you need to apply any code fix directly to kevinlawler/kona.
It will probably not be applied until approved by Kevin, me, or anyone else that Kevin has approved to do commits to the code.

**Comment by gitonthescene** [comment]
Okay.  I’ll just have to try it next time.  I’ll post to the developer list if I have issues.  Thanks for considering appropriate credit for my work though that was never my motivation.
