### ISSUE TITLE
Unexpected output trying to reproduce cross.

### ISSUE THREAD

**Issue by gitonthescene** [kevinlawler/kona#616]
I was trying to produce the function cross defined [here](http://lambda-the-ultimate.org/node/1323#comment-15369).

It doesn't work as offered there though I don't see why it shouldn't be as all the pieces are available in kona.

```
kona      \ for help. \\ to exit.

  cross:(,/,/:\:)/(),/:
  cross(1 2;3 4 5;6)
()/(,/,/:\:),/:[(1 2
   3 4 5
   6);]
```

Poking around, I could get this to work:

```
  {,/x,/:\:y}/(),/:(1 2;3 4 5;6)
(1 3 6
 1 4 6
 1 5 6
 2 3 6
 2 4 6
 2 5 6)
```

But the attempt to turn this into a function produces no output:

```
  {{,/x,/:\:y}/(),/:x}(1 2;3 4 5;6)
  
```
Moreover, this doesn't seem substantially different from the original version above.

**Comment by tavmem** [comment]
Tried this today ... and it works in Linux
I have not tried it in IOS nor in Windows.
If you are still having a problem please let me know (and in which OS).
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  {{,/x,/:\:y}/(),/:x}(1 2;3 4 5;6)
(1 3 6
 1 4 6
 1 5 6
 2 3 6
 2 4 6
 2 5 6)
```

**Comment by tavmem** [comment]
It works in IOS
```
$ ./k
kona      \ for help. \\ to exit.

  {{,/x,/:\:y}/(),/:x}(1 2;3 4 5;6)
(1 3 6
 1 4 6
 1 5 6
 2 3 6
 2 4 6
 2 5 6)
```

**Comment by tavmem** [comment]
It works in Windows
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  {{,/x,/:\:y}/(),/:x}(1 2;3 4 5;6)
(1 3 6
 1 4 6
 1 5 6
 2 3 6
 2 4 6
 2 5 6)
```
It looks like something that has changed in the source code since you filed this issue has alleviated the problem.

**Comment by gitonthescene** [comment]
I’ll try with a recent build when I’m in front of my desktop.  (An iMac FWIW)

**Comment by tavmem** [comment]
Found it.

"Checking out" the git commit of Jan 4, 2022, which would have been the current commit on Jan 9 (when you reported this issue), the function produces no output.
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  {{,/x,/:\:y}/(),/:x}(1 2;3 4 5;6)
  \\
```
On subsequent commits, the function also fails to produce output until the most recent commit of Aug 31, 2022.
Then, it produces output.
