### ISSUE TITLE
Regression (Related to each??)

### ISSUE THREAD

**Issue by gitonthescene** [kevinlawler/kona#620]
I've been working through the [Advent of Code](https://github.com/gitonthescene/AoK) using kona.  I got day4.txt working on [tio](https://tio.run/##VZDRbuIwEEXf5ytmk1Vim1nFYxJCHCHxH4AqSt8aURSQ6jYJv86Ow/ZhpcixZ@49d@z3P@8f5@Pj8Xa8HX2yPyf7pKaSGqqImbgmtyRHlrgkx@RKYtmviJckS0VOZI6cI16Ts7QmbkgM0gNwDnmJXCMzogVcIzp0S8QSXQlOig1yibxCrAFXyBZR9CKrABlZxBa5Qm4AYqMSyoxwEJ3rf3RRc4ORXqOrJACijSPOlRIGkiFhEiNEXMHPuf5p27lXzeM0EPPXcUy3kvz5EhyTZMA4l4tDRJBU6gTgdOw6b3/nCSX7@IZy0fkp3QvGP8Dr29UPJ283qc9Dq3iRZqe20ukgpm6b@fvc6XyCyT5Medhm99P0tF5vXi2xwiq1raWYpAEunR8GNYTd92FUyvALfumNziVGKtMutF@H/Fcqx3ZuTdsiTACfZz@MhZIv00WucxXaRdAT9H64j8XnOTdhunTF9QagjBl7bRZFoYRi7qbX2ywq@udE11urIl@nVkf/WNzNGKah95duZ8KhVX2rpKJHlfZb1mb26kng7ZNu/sPPfJUVMXUjy@PxFw) but it didn't work when I ran it at the command line.

The issue is that the following doesn't work in the current kona but does in the tio example linked above.

```
  bs:((0 0 1 1 1
  0 1 1 1 1
  1 1 1 0 1
  0 0 0 0 1
  0 0 0 0 0)
 (0 0 1 1 0
  1 0 0 1 1
  0 0 1 0 1
  0 1 0 1 1
  1 1 0 0 0)
 (1 1 1 1 1
  0 0 0 1 0
  0 0 1 0 0
  0 1 0 0 1
  1 1 0 0 1))
  b:bs 2
  b
(1 1 1 1 1
 0 0 0 1 0
 0 0 1 0 0
 0 1 0 0 1
 1 1 0 0 1)
  {|/(|/(&)/')'(x;+x)} b
1
  {|/(|/(&)/')'(x;+x)}'bs
```
The following workaround does in current kona:
```
  {|//{(|/(&)/')'(x;+x)}x}b
1
  {|//{(|/(&)/')'(x;+x)}x}'bs
0 0 1
```

[EDIT: I rand git bisect on this with the attached file (suffix changed)]
```
$ git bisect good; make; ./k day4.k
1f02a068912106f8f1f8cc14e0914aceb911877e is the first bad commit
commit 1f02a068912106f8f1f8cc14e0914aceb911877e
Author: Tom Szczesny <tom@new-host-2.home>
Date:   Wed May 15 16:19:57 2019 -0400

    pass dict by value

 src/kx.c |  2 +-
 src/kx.h |  2 +-
 src/p.c  | 26 +++++++++++++-------------
 src/p.h  |  4 ++--
 src/v.c  |  2 +-
 src/v.h  |  2 +-
 6 files changed, 19 insertions(+), 19 deletions(-)
make: Nothing to be done for `all'.
kona      \ for help. \\ to exit.

  4512
1924
$
```

[day4.k.txt](https://github.com/kevinlawler/kona/files/8123779/day4.k.txt)

**Comment by gitonthescene** [comment]
Similarly, this works on [tio](https://tio.run/##PU9BboMwELzvKyxzsC1CwE2kRLai5h@AUgMJihD0YFQZ0fTrdG1oLx7PzsyO3SXd52CWpTGjUZwSWjDB6DdCpj4aM533oxshqDFP5I3x2BNxzfTfTQponq3FtKnq@6OlQOsHHqZu7u2KYVghelqtFHE1m9WN8sarEBAAfWfV7OY4/eGRExf3nqrpVSh/gn22CvXcV@eSnMiRnEvtWQmAiePljRxweMJQpNgu9Y/NtSyhHq2f/PPwuV0aBgBDr2bcjSm/3V0n7crXnsXcy5pzTIpgFWgp1FYifOd8s1@5zPQUbZGh1wm2iWX5BQ) but is not working on the command line.

I think this is where the problem is coming from:

```
  mks[t[0]@t[1];t[0]]
(2 2 2 2
 2 3 4 6
 2 2 4 4
 2 3 4 7
 1 2 3 5
 1 2 3 6
 2 3 3 6
 2 3 3 5
 2 3 2 3
 1 2 2 5
 1 2 3 5
 1 2 3 5
 2 2 2 2
 2 2 4 4)
  {mks[x[0]@x[1];x[0]]}t

```
I'm not sure what's happening here but it's not returning any results when I try to turn that statement into a function.

To be clear, I'm mentioning tio because I believe it has an old version of kona on it.  The following workaround seems to work though.

```
 {mks@/(x[0]@x[1];x[0])}t
(2 2 2 2
 2 3 4 6
 2 2 4 4
 2 3 4 7
 1 2 3 5
 1 2 3 6
 2 3 3 6
 2 3 3 5
 2 3 2 3
 1 2 2 5
 1 2 3 5
 1 2 3 5
 2 2 2 2
 2 2 4 4)
```

Here is the input data: [day8.txt](https://github.com/kevinlawler/kona/files/7968018/day8.txt)

**Comment by tavmem** [comment]
I had similar results with this issue.

Using the "git checkout" for the commit of Jan 4, 2022 ```{|/(|/(&)/')'(x;+x)}'bs``` fails to produce output.
However, using the current commit (of Aug 31, 2022)
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  bs:((0 0 1 1 1
>>    0 1 1 1 1
>>    1 1 1 0 1
>>    0 0 0 0 1
>>    0 0 0 0 0)
>   (0 0 1 1 0
>>    1 0 0 1 1
>>    0 0 1 0 1
>>    0 1 0 1 1
>>    1 1 0 0 0)
>   (1 1 1 1 1
>>    0 0 0 1 0
>>    0 0 1 0 0
>>    0 1 0 0 1
>>    1 1 0 0 1))
  
  b:bs 2
  
  b
(1 1 1 1 1
 0 0 0 1 0
 0 0 1 0 0
 0 1 0 0 1
 1 1 0 0 1)
  
  {|/(|/(&)/')'(x;+x)} b
1
  
  {|/(|/(&)/')'(x;+x)}'bs
0 0 1
```
I will close this issue.
It can be reopened if I am missing something.
