### ISSUE TITLE
Output disappearing?

### ISSUE THREAD

**Issue by gitonthescene** [kevinlawler/kona#622]
Trying to solve [AoC day12](https://adventofcode.com/2021/day/12) with Kona and spotting more differences between kona on the command line and [with tio](https://tio.run/##VU5Lc4IwEL7nV1h0TKJBSi@dLkPRmV569UJnkFEeglVMmeIhqPjX6UYc2x7ybfZ77O7O3H3JqG3T6BCBsZDGwl4aJKvMtUzJZm2@fehmsybVIfo@6LbcakTZPObkmJtVobHcagF9c18jZjrr3NcqYpdHGw713zWJNjRk1U2a@wb5f0XHz241JjMzwReT2Eyx6gNjjbdYKs5AU2CrAeXUMI0F1TS5iQjT4eVsnZSr/4FTh82EjtkKB6yuC5yHJ06KHCYdKQrHFi/Pr8vPhI6ADoAW4HXRx5CTSgZFCJcix0L25T11tzhMMM5F19rh1IXfcAYnCFi/5q6E2lOO7Vwbeyz/fMdM9pb2sldzT4UNKUGI7lCSwElYOEEvdEfKASYUDx0J@zIYKdwsp0M8TIZnJlnGF6D4mfUVd5VngeQCiYaqhvRZwq2StO0P) which I assume means there's been a regression.

The following code produces no output from the command line, but does with tio:

```
data:"\n"\1_"
fs-end
he-DX
fs-he
start-DX
pj-DX
end-zg
zg-sl
zg-pj
pj-he
RW-he
fs-DX
pj-RW
zg-RW
start-pj
he-WI
zg-he
pj-fs
start-RW"
data:"\n"\1_"
start-A
start-b
A-c
A-b
b-d
A-end
b-end"
data:d,|:'d:(`$')'"-"\'data

data:data@&~|/{x=data[;y]}.'+(`end`start;!2)
lg:.+(`end,l;1,97>_ic'*:'$:'l:?data[;0])
sn[l]:~lg[l]
mp:.+(`end,?data[;0];(,()),data[;1]@=:data[;0])
f:{:[(#y)=n:y?x;1;(#y)=1+n;1;(#y)=1+n+(n _1_ y)?x]}
p:,,`start
c:{,/{:[`end=*x;:(,x)];n:mp[*x];(n@&lg[n]|(#x)=x?/:n),\:x}'x}
#(c)/p
```

Narrowing it down a bit something goes wrong during the recursion:
```
  c
{,/{:[`end=*x;:(,x)];n:mp[*x];(n@&lg[n]|(n(f)\:x)|(#x)=x?/:n),\:x}'x}
  1{,/{:[`end=*x;:(,x)];n:mp[*x];(n@&lg[n]|(n(f)\:x)|(#x)=x?/:n),\:x}'x}/p
(`A `start
 `b `start)
  2{,/{:[`end=*x;:(,x)];n:mp[*x];(n@&lg[n]|(n(f)\:x)|(#x)=x?/:n),\:x}'x}/p
```

Also, I seem not to be able to use the function c:
```
  c p
  1(c)/p
  2(c)/p
```

[EDIT: I ran git bisect on this with the attached file.  (suffix changed)]
```
e90be4eb391fc15998d6871b7117d68a363c6390 is the first bad commit
commit e90be4eb391fc15998d6871b7117d68a363c6390
Author: Tom Szczesny <tavmem@gmail.com>
Date:   Sat Nov 2 14:11:07 2019 -0400

    fix #566 and fix #549: recursions housed in subfunctions

 src/kx.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
make: Nothing to be done for `all'.
kona      \ for help. \\ to exit.

  54
"2021-12-06"
```
[day12.k.txt](https://github.com/kevinlawler/kona/files/8123705/day12.k.txt)

**Comment by gitonthescene** [comment]
Here's a different example which works in [tio](https://tio.run/##y9bNzs9L/P@/xMrQQMFUwVRZw9BAy1TLVFMhPqUosVzBiKtaTV@7Qke7ola95P9/AA):
```
  t:10 5 5#(10*5*5) _draw 2
  {&/+x,+x}'t
  
```

Further, this [doesn't work in tio](https://tio.run/##y9bNzs9L/P@/xMrQQMFUwVRZw9BAy1TLVFMhPqUosVzBiKtaTV@7Qke7ola95P9/AA), but I'm not sure why:
```
t:10 5 5#(10*5*5) _draw 2
{|/&/+x,+x}'t
```

This works as a [workaround](https://tio.run/##y9bNzs9L/P@/xMrQQMFUwVRZw9BAy1TLVFMhPqUosVzBiKtaTV@7Qke7ola95P9/AA), though:
```
t:10 5 5#(10*5*5) _draw 2
{|/(&)/+x,+x}'t
```

FWIW, this was all while trying to get the [day 4 problem](https://adventofcode.com/2021/day/4) from AoC2021 to work in [kona](https://tio.run/##NVBNbupADN77FFaokgx1lbFJCJkRUk7wLhCiioZNVZRWgEQghKtTD3rdWB77@/N8vX1999vHY7c9bV206aNNVFJOFRXETFySLEjIEuckTJITa78kXpCWgkRhQiLEKxJLK@KKlKA7ABHkBXKJzIgWcIUoKAvEHCUH0WGFnCMvEUvAJbJFVLzCCkBGVrBFLpArgLAoVOUpIRCYq//qiuYKg3qJUqgBBBoHOcnVDNRDzdRGFXEJf@/yb22fu@IZp4LgvwoxZan@zyM4OGnAkEtCiCCkkzIC6Lb7vbMvSUTRJvyhHtp3bhbG8LE7unGo47v9tx6mJEntS4TRJuF3k6SxXc9csjPvuHOsRblwPLk0nSnNF74wM@uDjI/DxMDP3o3j2cX3q@9d3Qz@7J0fh@ba3tJ0fjFrkyhOn5PuLm1ybn3ae5W@@Lq5PtFp373NLmaO4y1L48wkA71qsL4@t2aqs2ECOLjxHmdDLdPPPjue4Ng5VZ3fD41toXPjPA2Z6kMjbTO0Zv6aZcdOuwk@3RinQ3aoxay1TNAln3qmv5nH4xc).

**Comment by tavmem** [comment]
With the commit that I will make now:
```
$ rlwrap -n ./k
kona      \ for help. \\ to exit.

  data:"\n"\1_"
>  fs-end
>  he-DX
>  fs-he
>  start-DX
>  pj-DX
>  end-zg
>  zg-sl
>  zg-pj
>  pj-he
>  RW-he
>  fs-DX
>  pj-RW
>  zg-RW
>  start-pj
>  he-WI
>  zg-he
>  pj-fs
>  start-RW"
  data:"\n"\1_"
>  start-A
>  start-b
>  A-c
>  A-b
>  b-d
>  A-end
>  b-end"
  data:d,|:'d:(`$')'"-"\'data
  
  data:data@&~|/{x=data[;y]}.'+(`end`start;!2)
  lg:.+(`end,l;1,97>_ic'*:'$:'l:?data[;0])
  sn[l]:~lg[l]
  mp:.+(`end,?data[;0];(,()),data[;1]@=:data[;0])
  f:{:[(#y)=n:y?x;1;(#y)=1+n;1;(#y)=1+n+(n _1_ y)?x]}
  p:,,`start
  c:{,/{:[`end=*x;:(,x)];n:mp[*x];(n@&lg[n]|(#x)=x?/:n),\:x}'x}
  #(c)/p
10
  
  c p
(`A `start
 `b `start)
  
  1(c)/p
(`A `start
 `b `start)
  
  2(c)/p
(`c `A `start
 `b `A `start
 `end `A `start
 `d `b `start
 `end `b `start
 `A `b `start)
  
  t:10 5 5#(10*5*5) _draw 2
    {&/+x,+x}'t
(0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0)
  
  t:10 5 5#(10*5*5) _draw 2
  {|/&/+x,+x}'t
1 1 0 0 1 0 0 1 0 0
  
  t:10 5 5#(10*5*5) _draw 2
  {|/(&)/+x,+x}'t
0 0 0 0 1 0 1 0 0 0
```
