### ISSUE TITLE
implement -h http_port

### ISSUE THREAD

**Issue by kevinlawler** [kevinlawler/kona#79]
there is an existing -i feature that opens a port for ipc (does it need to be renamed IPC_PORT from PORT in the code?). create a -h option that opens a port HTTP_PORT for http communication (how to resolve conflicts?)

    k -h 8080

it should read in HTTP requests and echo them back by default

    GET / HTTP/1.1
    Host: 192.168.01.01
    Connection: keep-alive
    User-Agent: ...
    Accept: application/xml,....
    ...

If .m.h exists on the tree, .m.h should be applied as a one-argument function to the character vector representation of the request text. if .m.h returns _n, it should continue building the char vec. if it returns anything but _n, echo that value to the client as the response and reset. (so by default .m.h is {x}, in a sense, but don't put an unnecessary value on the tree)

we can deviate from and improve on this spec as necessary.

code will go into the `select` loop near the IPC code.

**Comment by tavmem** [comment]
Seems that a Kona server process could be started up with
k -i 1234
or a Kona http server process could be started up with
k -h 8080
but that you would not start up a server process that attempted to do both, as in
k -i 1234 -h 8080
Is that reasonable?

**Comment by tavmem** [comment]
Kevin wrote in the first post for this issue:
> (how to resolve conflicts?)

It would be fairly easy to resolve conflicts and differentiate treatment if we allow a Kona session to be either an IPC-server or an HTTP-server, but not both.
I plan to go this route, unless there are any objections.

**Comment by tavmem** [comment]
At this point, HTTP_PORT works as an alternate IPC_PORT, but you can only have -i or -h, not both.

**Comment by kevinlawler** [comment]
It should be fine for version 1 to have them separated like you suggest.

Possibly my remark on "conflicts" meant oversubscription: `-i 1234 -h 1234` 

If memory serves, there is an easy way to distinguish whether a socket is an IPC or HTTP connection. I think you get the port number, which would tell you, or you can check if the handshake contains a valid Kona network header. Each connection has an associated table entry, and the connection type could be stored there.

**Comment by bakul** [comment]
On Wed, 29 Apr 2015 09:16:19 PDT Kevin Lawler <notifications@github.com> wrote:
> 
> Possibly my remark on "conflicts" meant oversubscription: `-i 1234 -h 1234` 
> 
> If memory serves, there is an easy way to distinguish whether a socket is an 
> IPC or HTTP connection. I think you get the port number, which would tell you,
> or you can check if the handshake contains a valid Kona network header. Each
> connection has an associated table entry, and the connection type could be 
> stored there.

Binding the same port to two different protocols is asking
for trouble.  Just reject it.

**Comment by tavmem** [comment]
Status:  If you use the May 2 commit that adds 2 diagnostic statements, and start a Kona process on Terminal-1 with an HTTP_PORT activated you get
```
~/kona $ rlwrap ./k -h 8080
  HTTP_PORT recognized
```
I you start a second Kona process on Terminal 2 and start IPC:
```
~/kona $ rlwrap ./k
  3: `"127.0.0.1",8080
3
```
On Terminal-1 you get
```
listener activated on HTTP_PORT
```
All the above is as expected.
Now, close both Kona processes and start again.  On Terminal-1
```
~/kona $ rlwrap ./k -h 8080
  HTTP_PORT recognized
```
This time on Terminal-2 use cURL
```
~/kona $ curl http://127.0.0.1
SSH-2.0-OpenSSH_5.9p1-hpn13v11
Protocol mismatch.
curl: (56) Recv failure: Connection reset by peer
```
On Terminal-1, you get no message that "listener" was activated in Kona.
cURL never gets to the Kona process.
It seems that the "Protocoal mismatch" is raised in SSH
Not clear why ... yet.

**Comment by tavmem** [comment]
Next step: Try it with http-kit from https://github.com/http-kit/http-kit, instead of Kona.  
On Terminal-1
```
~/http-kit $ ./scripts/start_test_server
compile java test code
Listening for transport dt_socket at address: 9093
15:47:50.721 [main] INFO  org.eclipse.jetty.server.Server - jetty-7.6.1.v20120215
15:47:50.795 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:14347
15:47:50.893 [main] INFO  org.eclipse.jetty.util.ssl.SslContextFactory - Enabled Protocols [SSLv2Hello, SSLv3, TLSv1] of [SSLv2Hello, SSLv3, TLSv1]
15:47:50.896 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started SslSelectChannelConnector@0.0.0.0:9898
server started at 0.0.0.0:9090
```
On Terminal-2
```
~ $ curl http://0.0.0.0:9090
hello world
```
It worked!

**Comment by tavmem** [comment]
Next step: back to Kona.
On Terminal-1
```
~/kona $ rlwrap ./k -h 8080
  HTTP_PORT recognized
```
On Terminal-2
```
~ $ curl http://127.0.0.1:8080
curl: (56) Recv failure: Connection reset by peer
```
But on Terminal-1
```
listener activated on HTTP_PORT
```
We have listener activated!!!
The initial problem on Kona was that I neglected to add the port number to the cURL command.

Next step: Find out what is happening next in Kona, and why the connection is reset.

**Comment by tavmem** [comment]
Now, the default echo back works on Terminal-2

On Terminal-1
```
~/kona $ rlwrap ./k -h 8080        
K Console - Enter \ for help
```
On Terminal-2
```
~ $ curl http://127.0.0.1:8080
GET / HTTP/1.1
curl: (56) Recv failure: Connection reset by peer
~ $
```
Next step: Implement a rudimentary version of .m.h

**Comment by tavmem** [comment]
Now that #210 is done, we can use Kona on both terminals
On Terminal-1
```
  ~/kona $ rlwrap ./k -h 8080
K Console - Enter \ for help
```
On Terminal-2
```
  ~/kona $ rlwrap ./k
K Console - Enter \ for help

  (`"127.0.0.1";8080) 4: "GET / HTTP/1.1"
"GET / HTTP/1.1\r\n\000"
```

**Comment by tavmem** [comment]
m.h is a Kona function of one argument (the data received from the client).
If m.h is not defined, echo received data back to client.
If m.h is defined, execute m.h on the data received.
Next step: test for existence of m.h

**Comment by tavmem** [comment]
**Done:** The client now echos-back the message if .m.h does not exist on the server.
If .m.h does exist, then the client returns nil.

**Next:** Process the incoming data on the server with .m.h and have the client return the result.

**Comment by tavmem** [comment]
In the initial comment for this issue, Kevin wrote:
> If .m.h exists on the tree, .m.h should be applied as a one-argument function to the character vector representation of the request text.  If .m.h exists on the tree, .m.h should be applied as a one-argument function to the character vector representation of the request text. if .m.h returns _n, it should continue building the char vec.

There is a somewhat different spec on page 196 of kref.pdf:
> As long as .m.h returns nil, more data is read, in each instance becoming the next argument to the filter.

i.e., a one-argument filter vs. a multi-argument filter.
I assume (as a first cut of Kona) we would go with the kref spec.

**Comment by tavmem** [comment]
For the next step (single argument), I am adding two additional specs, which may be lifted later:
If .m.h does not exist, echo back.
**If .m.h exists, but is not type 7-3, send message ".m.h is not type 7-3"**
If .m.h is type 7-3, apply .m.h to the single arg and send back result.
**the single arg in .m.h must be "x", as in {#x} or {3*#x}.**

**Comment by tavmem** [comment]
An interesting side-effect of Kona's current implementation:
In Kevin's initial comment for this issue:
> (so by default .m.h is {x}, in a sense, but don't put an unnecessary value on the tree)

However, simply by executing
```
.m.h:{x}
```
in the server-process, you get 2 entries on the server-process TREE
```
(`k; .,(`x; ; ); )
(`m: .,(`h; {x}; ); )
```
Note in particular, that \`x is created in \`k and not in \`m

**Comment by tavmem** [comment]
After commit of 4/21/15 titled "process message on server w .m.h and return result"
**Client (w/o .m.h defined on server):**
```
  (`"127.0.0.1";8080) 4: "123"
"123\r\n\r\n"
```
**Server:**
```
  .m.h:{#x}
{#x}
```
**Client:**
```
  (`"127.0.0.1";8080) 4: "123"
"3"
```
**Server:**
```
  .m.h:{.5*#x}
{.5*#x}
```
**Client:**
```
  (`"127.0.0.1";8080) 4: "123"
"1.500000"
```
**Server:**
```
  .m.h:{|x}
{|x}
```
**Client:**
```
  (`"127.0.0.1";8080) 4: "123"
"321"
```

**Comment by tavmem** [comment]
Next step: 2 arguments.

**Comment by tavmem** [comment]
After commit of 5/24/15 titled: "2 args"
**Server:**
```
  .m.h:{x,y}
```
**Client:**
```
  (`"127.0.0.1";8080) 4: "123"
"\000"
  (`"127.0.0.1";8080) 4: "abcd"
"123abcd"
```
**Server:**
```
  .m.h:{(#x)+#y}
```
**Client:**
```
  (`"127.0.0.1";8080) 4: "123"
"\000"
  (`"127.0.0.1";8080) 4: "abcd"
"7"
```
**Next step:** 3 arguments.

**Comment by tavmem** [comment]
**Done:** The 3-arguments case now works in Linux.
**Next:** Verify that everything works in OSX and FreeBSD.  Get everything to work in Windows.

**Comment by tavmem** [comment]
A script for testing the 3-arg case on Windows::

**Server**
```
k -h 8080
  .m.h:{x,y,z}
```
**Client**
```
  (`"127.0.0.1";8080) 4: "aa"
"\000"
  (`"127.0.0.1";8080) 4: "bbb"
"\000"
  (`"127.0.0.1";8080) 4: "cccc"
"aabbbcccc"
```

**Comment by tavmem** [comment]
This issue is fully implemented for Linux.
For Windows, it will require a different implementation strategy, since fundamental featues such as "/etc/services" do not exist in Windows.

I am opening a new issue for the Windows implementation.

If the currently implemented functionality works when tested on OSX and FreeBSD, then I will be closing this issue.

**Comment by tavmem** [comment]
Update for OSX:
**worked** when I set up a Linux box as the http server, and an OSX box as the client.
**failed** when I set up an OSX box as the http server, and a Linux box as the client.

**Comment by tavmem** [comment]
The explanation for the worked/failed results above is probably:
The Linux box is hard-wired to my LAN with its own IP address.
The OSX box is using wireless and has the same IP address as my Windows laptop (which is wireless).
Will try with 2 terminal processes on the OSX box

**Comment by tavmem** [comment]
OSX works fine when both the server and client processes are on the OSX box.

**Comment by tavmem** [comment]
Works on FreeBsd when both the server and client processes are on the FreeBsd box.
