### ISSUE TITLE
Feature: sorting for dictionaries

### ISSUE THREAD

**Issue by kevinlawler** [kevinlawler/kona#9]
Update KC() ("K compare") to provide a sensible comparison function (results in {-1,0,1}) for dictionaries. This will let us sort dictionaries.

**Comment by tavmem** [comment]
Define a dictionary:
```
  d:.((`a;1);(`c;2 3);(`b;"abcde"))
  d
.((`a;1;)
  (`c
   2 3
   )
  (`b;"abcde";))
```

Then to sort d, use the function:
```
  {.+(k;x[k:{x@<x}(!x)])}d
.((`a;1;)
  (`b;"abcde";)
  (`c
   2 3
   ))
```
